### ISSUE TITLE
harmony package should likely not be in `utils` section

### ISSUE THREAD

**Issue by raisjn** [matteodelabre/toltec#105]
what section does it belong in?

**Comment by matteodelabre** [comment]
We should probably create a section for this kind of sketching app. The trouble is that xochitl will fit both in that new section and in the existing `readers` section. Any ideas about the name? `sketching`, `drawing` or `notetaking` come to mind.

**Comment by Eeems** [comment]
Any reason we can't have an application in more than one section?

A shorter term workaround here would be to not display the xochitl package since it's just there to help make launchers work.

**Comment by matteodelabre** [comment]
The Debian control file [only allows a single section per package](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-section), if I’m not mistaken. We could have something like a “main section” which is the one that is recorded in the package’s `Section:` field, and secondary sections which are used to classify the package in the generated index.

**Comment by matteodelabre** [comment]
We could also choose to totally ignore the package's `Section:` field, and only use the sections at the Toltec level. Opkg does not seem to make much use of it anyway.

**Comment by Eeems** [comment]
> 
> 
> We could also choose to totally ignore the package's `Section:` field, and only use the sections at the Toltec level. Opkg does not seem to make much use of it anyway.

Based on the sections that Debian uses (https://www.debian.org/doc/debian-policy/ch-archive.html#s-subsections) main, contrib, and non-free I think we should have a different category fiend we use for what we have been using section for. Instead, we should probably use the main/contrib/non-free idea for section.

**Comment by matteodelabre** [comment]
I think these docs are slightly confusing but the Debian `Section` field actually is not limited to the area name (main, contrib, non-free):

> The Section field should be of the form:
>
> — section if the package is in the main archive area,
> — area/section if the package is in the contrib or non-free archive areas.
>
> The Debian archive maintainers provide the authoritative list of sections. At present, they are: admin, cli-mono, comm, database, debug, devel, doc, editors, education, electronics, embedded, fonts, games, gnome, gnu-r, gnustep, graphics, hamradio, haskell, httpd, interpreters, introspection, java, javascript, kde, kernel, libdevel, libs, lisp, localization, mail, math, metapackages, misc, net, news, ocaml, oldlibs, otherosfs, perl, php, python, ruby, rust, science, shells, sound, tasks, tex, text, utils, vcs, video, web, x11, xfce, zope. The additional section debian-installer contains special packages used by the installer and is not used for normal Debian packages.

So that field is actually used for categorizing software, if I’m not mistaken. But we have no obligation to follow the Debian convention for this of course.

**Comment by Eeems** [comment]
> 
> 
> I think these docs are slightly confusing but the Debian `Section` field actually is not limited to the area name (main, contrib, non-free):

Ah, you are right. That's what I get for trying to do too many things at once. I didn't read it closely enough.
>
> So that field is actually used for categorizing software, if I’m not mistaken. But we have no obligation to follow the Debian convention for this of course.

I do think that only allowing one section is too limiting.

**Comment by raisjn** [comment]
> Any ideas about the name? sketching, drawing or notetaking come to mind.

Not sure, I feel like there are two separate categories here: drawing and notetaking, which could fit into "Image Manipulation" category and "Productivity" category. For harmony, it is "drawing" (and not productivity / notetaking). I don't have any preferences here other than "utils" is not right for harmony based on who its neighbors are.

**Comment by matteodelabre** [comment]
Good point—let's use `drawing` then.

**Comment by matteodelabre** [comment]
Fixed by #112.
