### ISSUE TITLE
Sort the sections alphabetically in the generated index page

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#106]
[The list of existing sections is computed using a Bash associative array.](https://github.com/toltec-dev/toltec/blob/6a6839e4e5f4ab930eb045680845d1eeb9301927/scripts/repo-build-web#L107) The keys of that array are then enumerated to generate the list of sections in the index page. The ordering appears to change with each build, which is probably because Bash is using a non-deterministic hashtable of some kind for storing associative arrays. It would be best to ensure that the order is consistent across builds by sorting the list of sections alphabetically.

**Comment by raisjn** [comment]
after comparing https://toltec.delab.re/stable/ and https://toltec.delab.re/testing/, i can no longer tell which style i prefer

**Comment by Eeems** [comment]
I think I'd prefer the list of all applications that you can sort by category instead. Maybe add a search box in the corner to filter the list. Obviously we don't have enough packages yet to warrant that. Fingers crossed this grows enough that it will.
