### ISSUE TITLE
build step doesn't run if there is no image

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#120]
Either we need to update our documentation to be clearer that build only happens if `image=` is populated, or still run it for simple things like patching files.

**Comment by matteodelabre** [comment]
Right. We could add a `prepare()` step that runs before the `build()` step, which would reinforce the fact that `build()` is intended only for building ARM binaries.

**Comment by Eeems** [comment]
Sure, as long as we properly document that `build()` requires an `image=`. We should also raise a warning at runtime if one exists without the other.
