### ISSUE TITLE
Simplify bootstrap

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#141]
The bootstrap script currently pulls down wget and then installs entware and toltec. I think it would be a good idea to remove most of the logic from the script. Instead it should pull down the safe wget, and then pull down the latest installation script from our server. That way we can push out changes without requiring the bootstrap script being updated, and our installation commands changing.

**Comment by Eeems** [comment]
The more I think about this the more I think it would make more sense to just implement #140 and to have hooks for re-enable. That way bootstrap doesn't have to change that often, but we have a mechanism to push out updates. We'll also have a mechanism to push out extra hooks based on specific packages.
The only hook I can think of right now would be restoring systemctl to where it was previously, as well as properly restoring any files that aren't in `/opt` or `/home/root`

**Comment by Eeems** [comment]
For restoring files that aren't in `/opt` or `/home/root` I'm guessing just reinstalling all packages that are installed will handle this.

**Comment by Eeems** [comment]
Now that we've got toltec-boostrap this might be lower priority.

**Comment by matteodelabre** [comment]
Addressed in #379.
