### ISSUE TITLE
Specify that users needs to be connected to Wi-Fi before running the install script

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#152]
Right now wget just complains about the site not being a valid domain.

**Comment by LinusCDE** [comment]
The wget from the 3 liner or the bootstrap script?

I think I had a basic ping test in the first script, to tell the user that he either has no internet access or working dns (which is rare). Having it in the bootstrap now would be mostly pointless though, as the user will most likely run the 3 liner and would require the complexity there.

EDIT: Maybe we should add a "Make sure you have a WiFi connected" to the readme.

**Comment by Eeems** [comment]
Likely from the 3 liner. Someone was asking for help on Discord. The readme might be enough.

**Comment by gbyl** [comment]
Fixed by https://github.com/toltec-dev/toltec/pull/423 and https://github.com/toltec-dev/toltec/pull/460
