### ISSUE TITLE
Why does it say that I have the packages but then say it cannot find them?

### ISSUE THREAD

**Issue by cindy-jth** [matteodelabre/toltec#156]
reMarkable: ~/ opkg upgrade
reMarkable: ~/ opkg update draft
Downloading https://bin.entware.net/armv7sf-k3.2/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Downloading https://toltec-dev.org/stable/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/toltec
reMarkable: ~/ opkg update nao
Downloading https://bin.entware.net/armv7sf-k3.2/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Downloading https://toltec-dev.org/stable/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/toltec
reMarkable: ~/ systemctl stop xochitl
reMarkable: ~/ systemctl start draft
Failed to start draft.service: Unit draft.service not found.
reMarkable: ~/ systemctl start xochitl
reMarkable: ~/ opkg install plato
Package plato (0.9.1-10) installed in root is up to date.
reMarkable: ~/ opkg upgrade plato
reMarkable: ~/ systemctl start plato
Failed to start plato.service: Unit plato.service not found.
reMarkable: ~/ systemctl restart plato
Failed to restart plato.service: Unit plato.service not found.

------------

reMarkable: ~/ opkg list-installed
ca-certificates - 20200601-1
draft - 0.2.0-14
entware-opt - 227000-3
entware-release - 1.0-2
entware-upgrade - 1.0-1
findutils - 4.7.0-2
grep - 3.6-1
libc - 2.27-11
libgcc - 8.4.0-11
libopenssl - 1.1.1h-1
libpcre - 8.44-2
libpthread - 2.27-11
librt - 2.27-11
libssp - 8.4.0-11
libstdcpp - 8.4.0-11
locales - 2.27-9
nao - 0.0.1-15
opkg - 2020-11-24-61b3c62d-1
plato - 0.9.1-10
remux - 0.0.1-20
simple - 0.0.1-15
terminfo - 6.2-1
wget - 1.20.3-4
xochitl - 0.0.0-1
zlib - 1.2.11-3
zoneinfo-asia - 2020d-1
zoneinfo-europe - 2020d-1
reMarkable: ~/ opkg find draft
draft - 0.2.0-14 - Launcher which wraps around the standard interface
reMarkable: ~/ systemctl start draft
Failed to start draft.service: Unit draft.service not found.

**Comment by raisjn** [comment]
i think it is:

```
opkg update
opkg upgrade
systemctl daemon-reload
systemctl start draft
```

as an example. if that doesn't work, you can uninstall and re-install a package with `opkg remove foo` and `opkg install foo`. 


PS: if you start draft, you have to stop xochitl.

**Comment by LinusCDE** [comment]
It should usually pick up the .service file without `daemon-reload`. Maybe your reMarkable updated in the mean time (had this happen yesterday and was irritated why remux didn't come up. The update went so fast, that I didn't notice it).

A mechanism for re-adding service files is still in the works. Try `opkg remove`ing and `opkg install`ing draft again. I'm not sure whether `opkg upgrade plato` would add a file that went missing on its own as it is supposed to work in /opt or another persistent directory only.

**Comment by cindy-jth** [comment]
I can't seem to remove draft or remux:

reMarkable: ~/ opkg update
Downloading https://bin.entware.net/armv7sf-k3.2/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Downloading https://toltec-dev.org/stable/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/toltec
reMarkable: ~/ opkg upgrade
reMarkable: ~/ systemctl daemon-reload
reMarkable: ~/ systemctl start draft
Failed to start draft.service: Unit draft.service not found.
reMarkable: ~/ opkg remove plato
Removing package plato from root...
reMarkable: ~/ opkg remove nao
Removing package nao from root...
reMarkable: ~/ opkg remove remux
Removing package remux from root...
Disabling remux
Failed to disable unit: Unit file remux.service does not exist.
You can force removal of packages with failed prerm scripts with the option:
	--force-remove
No packages removed.
Collected errors:
 * pkg_run_script: package "remux" prerm script returned status 1.
 * opkg_remove_pkg: not removing package "remux", prerm script failed

reMarkable: ~/ opkg remove draft
Removing package draft from root...
Disabling draft
Failed to disable unit: Unit file draft.service does not exist.
You can force removal of packages with failed prerm scripts with the option:
	--force-remove
No packages removed.
Collected errors:
 * pkg_run_script: package "draft" prerm script returned status 1.
 * opkg_remove_pkg: not removing package "draft", prerm script failed

reMarkable: ~/ opkg remove remux --force-remove
Removing package remux from root...
Disabling remux
Failed to disable unit: Unit file remux.service does not exist.
Collected errors:
 * pkg_run_script: package "remux" prerm script returned status 1.

reMarkable: ~/ opkg remove draft --force-remove
Removing package draft from root...
Disabling draft
Failed to disable unit: Unit file draft.service does not exist.
Collected errors:
 * pkg_run_script: package "draft" prerm script returned status 1.

**Comment by LinusCDE** [comment]
`Failed to disable unit: Unit file draft.service does not exist.`

So the file did not exist indeed. Most likely due to an official update.

Not entirely sure, but after your failed `opkg remove draft --force-remove` the package should be removed nontheless. Try installing it again now.

**Comment by LinusCDE** [comment]
Next time, it's probably easier for now to just take the draft.service from [here](https://github.com/toltec-dev/toltec/tree/stable/package/draft) and place it into `/var/lib/systemd/system/` ([source](https://github.com/toltec-dev/toltec/blob/0632dd0529d2a693f4736a73f6a830ca4a1e4558/package/draft/package#L47)).

(While on it, bumping #109 seems appropriate.)

**Comment by Eeems** [comment]
Sounds like we should update the uninstall logic to be more forgiving about service files not existing.

**Comment by LinusCDE** [comment]
Can we even do this? Probably just adding the service file as part of a script would make that work as far as I know rn.

**Comment by cindy-jth** [comment]
Two more semi related question: How do you get epubs and pdfs on Plato? And how do I remove amination_demo like files from opkg because I don't see them in the opkg list so I don't know where they are located? (I used the command for installing harmony on the harmony github page and it installed a lot of other files that I did not want.)

**Comment by Eeems** [comment]
> Can we even do this? Probably just adding the service file as part of a script would make that work as far as I know rn.

The uninstall script can easily check to see if a unit exists or not, and only attempt to disable it if it does exist, and is active: https://stackoverflow.com/a/53640320 and https://askubuntu.com/a/795242

**Comment by LinusCDE** [comment]
> How do you get epubs and pdfs on Plato?

Put the files in the folder `/home/root/plato-media` by default.

(Plato is installed to /opt/lib/plato and the Settings.toml has a default `[[libraries]]` entry with the directory of (`/opt/lib/plato/`)`media` which is a link to the above mentioned directory. The `Settings.toml` file is also actually a symlink to `/opt/etc/plato.toml` to make it seem more integrated. `ls -la /opt/lib/plato` shows all those links.)

> And how do I remove amination_demo like files from opkg because I don't see them in the opkg list so I don't know where they are located? (I used the command for installing harmony on the harmony github page and it installed a lot of other files that I did not want.)

amination_demo is part of [rmkit](https://github.com/rmkit-dev/rmkit/) which got split into multiple packages later (remux, harmony, ...). You probably installed rmkit at that time and still have it. @raisjn can tell you more about that.

**Comment by raisjn** [comment]
likely can delete `/home/root/apps` - that's where the harmony demo script installed stuff

**Comment by Cindy-Jie-01** [comment]
> Put the files in the folder `/home/root/plato-media` by default.
I did this but they did not show up in Plato. I also tried placing in the .reading-states folder under plato-media, but that did not work either :(

**Comment by LinusCDE** [comment]
What's the content of `/opt/etc/plato.toml`? The reading states stuff is generated automatically. (Deleting and re-creating the folder is no problem at all).

Or did you install the standalone (non-toltec) plato from the repos releases?
