### ISSUE TITLE
"opkg_conf_load: Could not lock /opt/tmp/opkg.lock: Resource temporarily unavailable."

### ISSUE THREAD

**Issue by cindy-jth** [matteodelabre/toltec#157]
reMarkable: ~/ opkg list-installed
Collected errors:
 * opkg_conf_load: Could not lock /opt/tmp/opkg.lock: Resource temporarily unavailable.

**Comment by Eeems** [comment]
Either you have another opkg call running, or the lock file wasn't cleaned up for some reason. If it continues to stay locked you can make sure no other opkg instance is running (`ps -a | grep opkg`) and then remove the lock file `rm /opt/tmp/opkg.lock`.

**Comment by cindy-jth** [comment]
reMarkable: ~/ ps -a | grep pkg
ps: invalid option -- 'a'
BusyBox v1.30.1 (2020-11-04 10:23:38 UTC) multi-call binary.

Usage: ps

**Comment by Eeems** [comment]
@Cindy-Jie-01 Whoops, forgot what version it was using. You can remove the `-a`, so just `ps | grep opkg`
