### ISSUE TITLE
Simple shapes (line, circle, rectangle, triangle)

### ISSUE THREAD

**Issue by MechEng70** [matteodelabre/toltec#178]
This is more of a feature/enhancement. Would it be possible to create a menu that inserts a selected shape.  Once selected, it goes into a resize/move state until a second shape is selected or the user selects off of the shape.  
Starting with the line, circle, rectangle and triangle would allow the user to create most of basic shapes.

**Comment by Eeems** [comment]
Did you open this on the wrong repository?
This project just hosts packages that can be installed on the reMarkable 1 or 2.

**Comment by MechEng70** [comment]
No, it was an idea.  
But from your comment, seems like it should not be here.  Thoughts on if there is somebody that would probably do something like this?  Wish I had the programming experience to do this.

**Comment by Eeems** [comment]
I think the place to ask for this would be on https://github.com/ddvk/remarkable-hacks. That said, I believe others have already asked, and @ddvk has said that it's not something he's been willing to try to implement due to how difficult it is.

**Comment by raisjn** [comment]
fwiw, i'm working on something like this but not inside xochitl. i'll ping on this thread when there's a UI to play with

**Comment by MechEng70** [comment]
Let me know if you need testers?

Would be happy to help.
