### ISSUE TITLE
Add timezone info package

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#179]
The reMarkable doesn't come with the full set of timezone information. So timezones listed by `timedatectl` as on the device are not actually selectable. We should add a package that contains the full set and likely install it by default.

**Comment by matteodelabre** [comment]
Note that the `zoneinfo-*` packages from Entware (of which `zoneinfo-asia` and `zoneinfo-europe` are installed by default) already install timezone information to `/opt/share/timezone/`. So we could simply defer to these packages by symlinking `/usr/share/timezone` to `/opt/share/timezone`. We also need to install `zoneinfo-core` for this to work (strangely, it is not installed by default), otherwise key files like `/opt/share/timezone/zone.tab` are missing.

**Comment by Eeems** [comment]
Hmm, but does this work nicely with `timedatectl`?

**Comment by matteodelabre** [comment]
Just tested it on my device and it works (both `list-timezones` and `set-timezone`).

**Comment by Eeems** [comment]
So I guess the tzdata package isn't needed?

**Comment by MechEng70** [comment]
RM2 here (without installing anything):

```
reMarkable: ~/ timedatectl set-timezone America/Los_Angeles
reMarkable: ~/ timedatectl
                      Local time: Tue 2021-01-05 08:12:21 PST
                  Universal time: Tue 2021-01-05 16:12:21 UTC
                        RTC time: Tue 2021-01-05 16:12:22
                       Time zone: America/Los_Angeles (PST, -0800)
       System clock synchronized: no
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
reMarkable: ~/
```

**Comment by matteodelabre** [comment]
> So I guess the tzdata package isn't needed?

@Eeems Yes. It seems to be redundant with the Entware packages. As an added bonus, installing timezone info to `/opt` saves space on the root partition.

> RM2 here (without installing anything)

@MechEng70 `America/Los_Angeles` is shipped by default with the reMarkable. Try another timezone like `Africa/Abidjan` which although it is listed in `timedatectl list-timezones` should give you an error.

**Comment by Eeems** [comment]
Does zoneinfo-core contain `zdump` or `zic`?

**Comment by matteodelabre** [comment]
It looks like `zoneinfo-*` packages only contain zone definitions and no binaries.

**Comment by MechEng70** [comment]
@matteodelabre Confirmed that "Africa/Abidjan" does give an error on RM2.

```
reMarkable: ~/ timedatectl set-timezone Africa/Abidjan
Failed to set time zone: Invalid time zone 'Africa/Abidjan'
```

**Comment by matteodelabre** [comment]
@MechEng70 Thanks for testing!

**Comment by Eeems** [comment]
> 
> 
> It looks like `zoneinfo-*` packages only contain zone definitions and no binaries.

Alright I'll take a quick look to see if entware has them elsewhere, if not I'll rename the package and only include those binaries.

**Comment by matteodelabre** [comment]
To make everything work smoothly, we’ll also need to create the symlink from `/usr/share/timezone` to `/opt/share/timezone` in the bootstrap script. But since we don’t have an uninstall script (maybe we ought to have one?), I’m not sure what is the best way to restore the rM-provided timezone data.

**Comment by Eeems** [comment]
The best way would be to pull it directly from an update archive to be honest. Perhaps we should be using a bind mount instead of symlinking? That way we don't have to worry about restoring?

**Comment by matteodelabre** [comment]
Good idea, I forgot about bind mounts. I'll open a PR to add this to the install script tomorrow.

**Comment by Eeems** [comment]
> Good idea, I forgot about bind mounts. I'll open a PR to add this to the install script tomorrow.

Which PR is that ;P

**Comment by matteodelabre** [comment]
Is it tomorrow yet?

**Comment by Eeems** [comment]
Opened #213
