### ISSUE TITLE
[feature] add support for per package docker images

### ISSUE THREAD

**Issue by raisjnn** [matteodelabre/toltec#2]

**Comment by LinusCDE** [comment]
Seems to already be WIP.

I just wanted to create github actions for publishing the images, but saw that those were already added. Would be nice to also push them to hub.docker.com though as they're more easy to find there.

**Comment by matteodelabre** [comment]
I’m currently looking into this. :-) Why push them to the Docker Hub? Is there a use-case for re-using the images outside of this project?

**Comment by Eeems** [comment]
If you want to do the build locally to test, it's nice to not have to wait for the image to build.

**Comment by matteodelabre** [comment]
Fixed by 4679813e76bd72ca803ea214cb811cbbffb87263 and 2834d5bb7f0131a7465172b01ed8566ee7496e88. The images are pushed to the GitHub Container Registry (ghcr.io), which allows anyone to pull images, so this should be functionally equivalent to pushing to the Docker Hub.
