### ISSUE TITLE
how-to-enable says to disable shutdown.target

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#207]
![image](https://user-images.githubusercontent.com/1176979/104115170-72a12680-52c9-11eb-9ad3-672b5e7278e5.png)

We should probably filter out anything that isn't a *.service file.

**Comment by LinusCDE** [comment]
Found that a while as well with remux. I somehow forgot to start a fix on it.

I added a quick fix in a new pr for this. Conversation and changes can be continues there.
