### ISSUE TITLE
Specify required packages on host

### ISSUE THREAD

**Issue by LinusCDE** [matteodelabre/toltec#210]
When running various make commands, there are some expected packages required that are nowhere mentioned aside from github workflow files.

These are currently `bsdtar` and `tree`. While common, these are often not preinstalled. Soon to come may also be `jo` `jq`.

We should probably mention that either in the `READM.md` or `docs/building.md`.

**Comment by Eeems** [comment]
Perhaps there should be a quick check in the Makefile as well to confirm they exist?

**Comment by matteodelabre** [comment]
Agreed. As an aside, I’m currently working on a Python rewrite of the build tooling (#211), which will replace those required binaries with required Python packages.

**Comment by matteodelabre** [comment]
See https://github.com/toltec-dev/toltec/blob/testing/docs/building.md.
