### ISSUE TITLE
Rewrite tooling scripts in Python

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#211]
I’m currently rewriting the tooling scripts from Bash to Python.

Goals of the rewrite:

* Contain it to only the tooling scripts. Package recipes should be unaffected by the change.
* Make it easier to add features to the tooling scripts, which is quite a challenge in their current Bash form.
* Add more sanity checks when parsing and building recipes.

If you’d like to suggest a specific feature for the rewrite, feel free to comment below. I’d like to keep the rewrite as focused as possible so that we can quickly merge it and move to other more productive things.

**Comment by Eeems** [comment]
#85 #210 #8 and perhaps poke at #45

**Comment by matteodelabre** [comment]
In the interest of not blocking other tasks that depend on this, I’m planning on splitting this in three PRs:

- [x] Rewrite of `package-build` and `repo-build` (#218).
- [x] Rewrite of `repo-build-web` (#266).
- [ ] Rewrite of `repo-check`.

**Comment by matteodelabre** [comment]
Closing this since almost everything has been rewritten to Python, except for the `repo-check` script, which is ununsed anyway since we haven’t really integrated reproducible builds into our workflow yet.
