### ISSUE TITLE
Remux outdated

### ISSUE THREAD

**Issue by aidanjalili** [matteodelabre/toltec#233]
Remux is currently on version 0.1.7 (you can see for yourself at https://github.com/rmkit-dev/rmkit/tree/master/src/remux). This is a current stable release, however opkg has this version neither at the stable nor testing repo...

**Comment by raisjn** [comment]
next release will be 0.1.7, i haven't made the PR on toltec yet

**Comment by aidanjalili** [comment]
Ah I see, thx

**Comment by raisjn** [comment]
you can grab the latest remux binary from build.rmkit.dev/master/latest/files in the meanwhile

**Comment by aidanjalili** [comment]
Thanks -- Will do that actually.
