### ISSUE TITLE
Install zoneinfo-core by default

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#237]
https://github.com/toltec-dev/toltec/pull/182#issuecomment-761695819

Likely our current bootstrap in testing has issues with timedatectl due to the zoneinfo  bind mount and should be tested.

**Comment by matteodelabre** [comment]
Should we override the zoneinfo-core package with our version that additionally installs the bind mount?

**Comment by Eeems** [comment]
And remove the bind mount from toltec-bootstrap? That might be a good idea.

**Comment by matteodelabre** [comment]
@Eeems Can this be closed, since we moved the bind mount to the `zoneinfo-utils` package in #303?
