### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#239]
- [x] Package request
- [x] Package issue
- [x] Documentation issue

More?

**Comment by danshick** [comment]
Security issue/patch request?

I guess that's a package issue.

**Comment by Eeems** [comment]
> Security issue/patch request?
> 
> I guess that's a package issue.

It's either just a PR with a fix if it's not a large concern, or they follow the security policy: https://github.com/toltec-dev/organization/blob/main/docs/security.md
