### ISSUE TITLE
Update fingerterm to newest source?

### ISSUE THREAD

**Issue by nullstalgia** [matteodelabre/toltec#242]
Hi, I wasn't sure how else to do this since I couldn't find a similar request in the issues.

But  dixonary's fingerterm-reMarkable repo has had a lot of updates (toltec timestamp says 2017), namely being able to turn off the large feedback when using the keyboard by adding

```
showVisualKeyPressFeedback=false
keyPressFeedback=false
```

to `[ui]` in `/home/root/.config/FingerTerm/settings.ini`

Should I send a PR into testing with updated SHA's? Or is it best if we send in issues for the package devs/toltec maintainers to handle.

**Comment by raisjn** [comment]
send a PR works great, thank you!
