### ISSUE TITLE
rm2fb: disable LD_PRELOAD for busybox services

### ISSUE THREAD

**Issue by raisjn** [matteodelabre/toltec#248]
from https://github.com/ddvk/remarkable2-framebuffer/issues/35#issuecomment-762977355, we need to disable the LD_PRELOAD in /lib/systemd/system/busybox-udhcpd@.service and /lib/systemd/system/busybox-ifplugd@.service (and probably more).

one way could be to add the `Environment=LD_PRELOAD=` line to the systemd services we think should have rm2fb client shim skipped.

**Comment by Eeems** [comment]
What about other service files that are running? They likely have the same error.

I'm thinking it might make more sense to create a default environment file that services in toltec include, and only populate that with the LD_PRELOAD environment variable on the rM2.

**Comment by raisjn** [comment]
yeah, that sounds reasonable. the only thing remaining would be to add that include to xochitl.service (bc xochitl needs rm2fbclient turned on) - which we don't necessarily control and can't expect that the owner of the tablet won't modify.

**Comment by Eeems** [comment]
The xochitl package could handle setting that as part of configure.

**Comment by matteodelabre** [comment]
With #310, LD_PRELOAD is not used anymore to inject the rm2fb client shim into apps (except for KOReader). The system-wide preload configuration was dropped. This should solve this issue.
