### ISSUE TITLE
Missing extraction formats in python tooling

### ISSUE THREAD

**Issue by jonahweissman** [matteodelabre/toltec#259]
The packaging documentation says that `.tar.xz` and `tar.bz` [are supported](https://github.com/toltec-dev/toltec/blob/testing/docs/package.md#source), but the new python tooling [does not support these two formats](https://github.com/toltec-dev/toltec/blob/testing/scripts/toltec/util.py#L105-L129). In addition, it [does not check the return value](https://github.com/toltec-dev/toltec/blob/testing/scripts/toltec/builder.py#L194) of `auto_extract` to catch unsupported formats.

**Comment by matteodelabre** [comment]
Thanks for the report @jonahweissman. Opened #260 to fix this.
