### ISSUE TITLE
Add CI to PRs

### ISSUE THREAD

**Issue by raisjnn** [matteodelabre/toltec#27]
it would be really nice if when there is a PR, it kicks off a github action that figures out what packages are affected and builds them, verifying that there are no obvious build errors. 

a package is affected if 1) it was modified or 2) its image (or image ancestor) was modified

**Comment by matteodelabre** [comment]
I agree on the general idea of adding CI to PRs. However, detecting which packages exactly are affected by a PR might be tedious. How about simply checking that all packages still build without error?

**Comment by raisjnn** [comment]
Doing full build is fine (assuming we pledge to keep our builds below some max). it needs to be done on pull requests and attached to the PR itself so it can be seen at a single glance (and ideally help me avoid merging broken packages into testing like I did last night)

**Comment by matteodelabre** [comment]
Fixed by 3e0491a8c01d080e38a6781630f34cd861682fc6. See #29 for an example of PR on which the check was run.

**Comment by raisjnn** [comment]
very nice, amazing work! (i noticed it is doing partial rebuild in the log for #29)

**Comment by raisjnn** [comment]
might also be nice to have the script do an `ls -R` or `tree` on the $pkgdir so we can see what went into the package just by looking at logs

**Comment by matteodelabre** [comment]
> might also be nice to have the script do an `ls -R` or `tree` on the $pkgdir so we can see what went into the package just by looking at logs

@raisjnn Done in 59720ca2a99c4ae881a311a934fd45d7d544bace.
