### ISSUE TITLE
Exiting any Toltec-installed app freezes RM2 - hard reboot necessary

### ISSUE THREAD

**Issue by jebediah2** [matteodelabre/toltec#275]
Installed rm2fb, Toltec and remux launcher on my RM2 today as per documentation. Everything works fine. Installed nao, reTris and KOReader. Remux interface and apps work fine, but whenever I exit them and should be taken back to xochitl, the tablet freezes and I have to press the power button many times to perform a hard reset. This doesn't happen when I exit remux launcher interface, only when I select an app from there, and try to come back from one of them.

**Comment by raisjn** [comment]
remux doesn't recognize when an app exits, so if you exit an app, you will just see the last screen drawn. 

you should still be able to bring up remux and switch back to xochitl (Remarkable app) when this happens. if you can't, next time it happens can you grab logs (`journalctl -u remux`) through ssh and post them in an issue on the rmkit github? thanks!

(closing as off topic for toltec, sorry)

**Comment by jebediah2** [comment]
My bad for not figuring out it's normal behaviour in remux. I had assumed those "Exit" buttons would be recognised no matter the launcher used. I thought it was more to do with the underlying toltec install. Thanks for clearing this up!

**Comment by raisjn** [comment]
np, I'll add something to the docs or faq to make it clear what is happening
