### ISSUE TITLE
checksum error

### ISSUE THREAD

**Issue by zohar-sarig** [matteodelabre/toltec#278]
Hi, 
Am trying to install toltec on RM1. 
Following the instruction, I get error in checksum.
Can anyone advise what seems to be the reason.
Thanks 

![Toltec installation error](https://user-images.githubusercontent.com/78812359/107396006-099a1200-6b06-11eb-93e8-697e1265730b.jpg)

**Comment by Eeems** [comment]
@matteodelabre did the last merge fail to update the checksum?

**Comment by zohar-sarig** [comment]
I seems OK now with  the new checksum.
So I assume it is safe to continue (?)

![Toltec installation](https://user-images.githubusercontent.com/78812359/107398636-7e6e4b80-6b08-11eb-9955-40acc5ca8c26.jpg)

**Comment by Eeems** [comment]
Ah, so you were using an old checksum. Always use the latest checksum from https://toltec-dev.org or the readme. Yes it's safe to continue.

**Comment by zohar-sarig** [comment]
Perfect. Thank you so much 👍
