### ISSUE TITLE
Make a github release for each merge to stable

### ISSUE THREAD

**Issue by lambada** [matteodelabre/toltec#290]
Whenever you merge to stable could you cut a new tag + github release? That way I can subscribe in github for release notifications so I get prompted to go and update the remarkable :slight_smile:
The only other closest option would be to get notified of all PR activity on it which... is a bit much as just an end user :slight_smile:
GitHub.

It looks like github actions exist for making a release so it should be fairly straight forward to add into the github actions stable workflow.

**Comment by danshick** [comment]
I think an [ISO week date](https://en.m.wikipedia.org/wiki/ISO_week_date) would make a reasonable tag.

**Comment by LinusCDE** [comment]
Seems like a nice idea. I first though it be too much hassle, but GH Actions should do the trick.

Otherwise a quick solution would be to use almost any RSS reader to subscribe to commits to the stable branch on this url: https://github.com/toltec-dev/toltec/commits/stable.atom

**Comment by matteodelabre** [comment]
I didn’t know GitHub published RSS feeds, thanks @LinusCDE! (I couldn’t find any documentation for them though.) Does this fit your use case @lambada?

**Comment by lambada** [comment]
Not particularly, if only because I don't actually use an RSS reader these days, though I could probably make it work by finding an RSS -> email service

**Comment by danshick** [comment]
Even with the RSS option, I think tagging releases is doable.
