### ISSUE TITLE
Provide automatic uninstall of Toltec and all installed packages

### ISSUE THREAD

**Issue by danshick** [matteodelabre/toltec#295]
We should have a single command approach to uninstalling all packages and reverting the bootstrap script.

**Comment by LinusCDE** [comment]
Good point. Thought of this some time ago as well.

@bbyucca Those is my crude routine I use when I need to rid my device of 99,9% toltec stuff for testing purposes. It's fairly crude but should do the job hopefully safely.

<details>
<summary>EDIT (from @matteodelabre): Please use <tt>toltecctl uninstall</tt>. The procedure below is outdated.</summary>
Run these commands (some may not apply if you haven't installed it)
- Remove oxide if installed. Maybe run it twice `opkg remove --force-remove fret erode rot decay tarnish oxide`
- Remove remux and/or draft if installed: `opkg remove remux ; opkg remove draft`
- Remove rm2fb (important!): `opkg remove rm2fb`
- Remove zoneinfo-utils: `opkg remove zoneinfo-utils`
- Ensure xochitl will autostart on next boot `systemctl enable xochitl`
- Disable mounting opt on next boot: `systemctl disable opt.mount`
- Run `df`. If you spot a mount at /usr/share/zoneinfo or similar stop right here! I haven't considered removing that here and a reboot may cause problems! Or try finding the same .mount file like with opt.mount on your own and do the same as with opt.mount.
- Reboot device: `reboot`

After reboot:
 - Ensure with `df` that `/opt` is not listed anymore
 - Remove the opt.mount file: `rm /lib/systemd/system/opt.mount`
 - Delete all toltec/entware related stuff (this may include precious configs of software which was in `/opt/etc`!): `rm -r /home/root/.entware`
 - Delete bootstrap and renable scripts: `rm /home/root/{bootstrap,entware-reenable}`
 - If installed, remove oxide configs: `rm -r /home/root/.config/Eeems`
 - Remove the `export PATH=/opt/... something something` line from `/home/root/.bashrc`.
 - Reboot device to be sure everything went well. Everything toltec/entware should be gone now.
</details>

**Comment by Eeems** [comment]
https://eeems.website/toltec/#comment-5264461858 might be useful as well (scroll to comments and open them)

**Comment by danshick** [comment]
<details>
<summary>EDIT (from @matteodelabre): Please use <tt>toltecctl uninstall</tt>. The procedure below is outdated.</summary>
For the sake of simplicity:


> You'd need to remove all the packages you installed. You can do that with the following:
> ```
> packages=$(opkg list-installed | while read -r inst_line; do
> pkg=$(echo "$inst_line" | awk '{ print $1 }')
> pkg_ver=$(echo "$inst_line" | awk '{ print $3 }')
> opkg files "$pkg" | grep -v /opt | grep -v "is installed on root" | grep -v /home/root > /dev/null && echo "$pkg $pkg_ver"
> done)
> echo -e "${packages[@]}" | sed 's/ /\0/g' | sort | uniq -d | awk '{print $1}' | xargs -r opkg remove
> ```
>After which make sure xochitl is enabled: systemctl enable xochitl
>
>Disable the mount point: `systemctl disable opt.mount`
>
>Reboot your device.
>
>Remove toltec files: `rm -r /home/root/{.entware,bootstrap,entware-reenable}`
</details>

**Comment by ghost** [comment]
@LinusCDE  Thank you so much. It's indeed an elaborate scheme.  I think I'll wait a bit before removing toltec. Currently I'm using the ddvk KOReader autoinstaller, but everything is under very active development. I'm currious how this will evolve. Perhaps with an automated uninstall.  KOReader is currently everything I need, but perhaps other programs become interesting after using the rM2 for a longer period.

**Comment by matteodelabre** [comment]
This would be a welcome addition. I think we could group together commands that relate to managing the Toltec installation (i.e., re-enable, uninstall, and maybe select branch/download PR artifacts as in #223) in a script stored into `~/.local/bin` (so that it persists system upgrades).

**Comment by matteodelabre** [comment]
I’ve opened #303 to migrate management of the `/usr/share/zoneinfo` bind mount out of the bootstrap script and into the `zoneinfo-utils` package. With this patch, we won’t have to bother thinking about removing this bind mount in the uninstall script (it will be implicitly removed when we uninstall the `zoneinfo-utils` package).

**Comment by matteodelabre** [comment]
> This would be a welcome addition. I think we could group together commands that relate to managing the Toltec installation (i.e., re-enable, uninstall, and maybe select branch/download PR artifacts as in #223) in a script stored into `~/.local/bin` (so that it persists system upgrades).

I implemented this approach in #356.

**Comment by matteodelabre** [comment]
`toltecctl uninstall` is now available in stable and testing.
