### ISSUE TITLE
Support for system update 2.6

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#322]
A new official system update, 2.6, is being rolled out to users. [Most system libraries have been updated](https://github.com/toltec-dev/toolchain#version-matrix) in this new version, which makes apps compiled for previous versions incompatible. In particular:

* Qt was updated from 5.11.3 to 5.15.1 and the libqsgepaper.a library does not work as-is. This is because the library interfaces with private Qt classes whose API have changed between the two versions (see Eeems/oxide#187, sandsmark/recrossable#15, khanhas/zshelf#3, dixonary/fingerterm-reMarkable#8, dps/remarkable-keywriter#18).
* libcrypto.so was updated from 1.0.2 to 1.1, which causes the apps that use this library to not work unless the old lib is copied (see pl-semiotics/rM-vnc-server#8).
* Method signatures in xochitl and remarkable-shutdown, used by rm2fb have changed (see ddvk/remarkable2-framebuffer#18, ddvk/remarkable2-framebuffer#55, rmkit-dev/rmkit#117).

[A new release of the Toltec toolchain](https://github.com/toltec-dev/toolchain/releases/tag/v2.0) was made to support building apps that target the new 2.6 update. However, most packages compiled for 2.6 will not work for 2.5, and vice-versa. Our current plan is to take advantage of the new features in #310 to create two separate repos containing packages for each of the two versions.

**Comment by raisjn** [comment]
rm2fb needs to update server to point at xochitl instead of remarkable shutdown, as there are new waveform modes (issue 56 in rm2fb) 

as part of this, rm2fb server should check that the preload exists before running, otherwise it will invoke xochitls main and run two at once if someone blows the home partition away

**Comment by matteodelabre** [comment]
Just released toolchain v2.0.1 to fix some crashes that were seen on Qt apps such as fingerterm and recrossable.

**Comment by matteodelabre** [comment]
Note to users: If you upgraded to 2.6, you can use the `switch.sh` script (followed by a reboot of your device) in https://github.com/ddvk/remarkable-update to temporarily roll back to 2.5.

**Comment by JanLuca** [comment]
@matteodelabre May I ask why the branch `package/support-2.6` with the updated packages is not merged yet? I compiled some of them manually and they just seem to work well on my rM2 with release 2.7. Are there still some issues and/or is some beta testing wished? :)

**Comment by Eeems** [comment]
@JanLuca Probably because we haven't opened a PR for it yet, and we still have some larger work in the testing branch we need to solve first. That is a good point though, @matteodelabre when do you plan on opening a PR for 2.6 support?

**Comment by matteodelabre** [comment]
It’s been a little while since I last worked on that branch, but if I remember correctly, there were some packages that didn’t build because the 2.x toolchain uses a newer version of gcc. I’ll try to open a PR this week.

**Comment by matteodelabre** [comment]
⩾2.6-compatible packages have now reached the testing branch (ping @JanLuca).
