### ISSUE TITLE
Downgrading to 2.5 after Qt problems on 2.6

### ISSUE THREAD

**Issue by kevinkuhl** [matteodelabre/toltec#333]
Hello everyone,

Thanks for the nice work.

This latest upgrade to 2.6 brought a lot of problems for Qt apps, is there any documented way of downgrading RM to a previous version?

Best

**Comment by Ameb** [comment]
There is a script to switch on [ddvk/remarkable-update](https://github.com/ddvk/remarkable-update).

**Comment by matteodelabre** [comment]
I’m closing this in favor of #322. Thanks @Ameb for your answer!

**Comment by kevinkuhl** [comment]
Thank you! I'm rolling it back to 2.5
