### ISSUE TITLE
Improve documentation for how to switch to the testing branch

### ISSUE THREAD

**Issue by gtsiam** [matteodelabre/toltec#341]
I tried to switch to the testing branch for the newer koreader version. The [documentation](https://github.com/toltec-dev/toltec/blob/stable/docs/branches.md) isn't all that clear in what I need to do for an existing toltec installation:

> To use the testing branch, update the /opt/etc/opkg.conf file on an existing install

Yes, update _how_? Well, after some searching, I'm pretty sure what I'm supposed to do is change the package feed, from:
```
src/gz toltec https://toltec-dev.org/stable
```
to
```
src/gz toltec https://toltec-dev.org/testing
```

However this still gives me the following error when I try `opkg update`:
```
Downloading https://toltec-dev.org/testing/Packages.gz
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 404 Not Found
*** Failed to download the package list from https://toltec-dev.org/testing/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://toltec-dev.org/testing/Packages.gz, wget returned 1.
```
At least at the time of writing this issue, both https://toltec-dev.org/testing/Packages.gz and https://toltec-dev.org/testing/Packages return 404.

**Comment by matteodelabre** [comment]
**Note:** This comment is outdated, there is now a simpler way to switch to the testing branch. Refer to the comment at the end of this thread.

~Hi @gtsiam, thanks for your report. You’re right that the documentation isn’t very precise as to how one can switch to the testing branch. This is definitely something that we plan on improving in the future; we’ve been discussing the addition of a script to switch branches automatically for some time now. There are several other issues with a higher priority that we’re working to address first, though.~

~We’ve recently changed the repository layout of the testing branch to better separate packages that work on rM1 only from those that work on rM2 only (see #310 for details). This layout change hasn’t landed in stable yet, hence the difference you’re seeing between <https://toltec-dev.org/stable> and <https://toltec-dev.org/testing>. With this new layout, the packages are now sorted into subfolders depending on which devices they support.~

~To switch to the testing branch, you’ll therefore need to update your Opkg configuration (located in `/opt/etc/opkg.conf`) for the new layout, as follows.~

```diff
-src/gz toltec https://toltec-dev.org/stable
+arch rmall 200
+arch rm1 250
+src/gz toltec-rmall https://toltec-dev.org/testing/rmall
+src/gz toltec-rm1 https://toltec-dev.org/testing/rm1
```

~If you’re using a reMarkable 2, you’ll need to replace all of the three occurrences of `rm1` above with `rm2`. After doing this change, run `opkg update` and `opkg upgrade` and you should be all set.~

~Note that you’re more likely to encounter bugs when using the testing branch. When you find one, it would be much appreciated if you could report it in a new issue in this repository. Thanks!~

**Comment by matteodelabre** [comment]
You can now switch between testing and stable by running `toltecctl switch-branch testing` or `toltecctl switch-branch stable`. This is documented here: https://github.com/toltec-dev/toltec/blob/stable/docs/branches.md#release-branches.
