### ISSUE TITLE
Toltec-wrapper.conf and Lamy Pen

### ISSUE THREAD

**Issue by ademasi** [matteodelabre/toltec#351]
Thank you for toltec, its is a super useful project.

I have been testing the "testing" branch on my RM1. I update the packages and I was not able understand why my Lamy Pen button was not working anymore. It is handle by the patched version of xochitl and a qt plugin. Normally remux take care of starting xochitl with the good command line to load the plugin. 

But I discovered that the toltec-wrapper file cause issues by imposing `/opt/bin/xochitl --system` , instead of `/opt/bin/xochitl --system -plugin evdevlamy` , at least for my usage.

Is it not possible to make it dynamic ?  Like remux does by reading ondisk service file ?

Regards, Alex.

**Comment by Eeems** [comment]
How are you launching xochitl? Draft, Oxide, and Remux all handle launching xochitl in different ways. It also requires you to have ddvk-hacks installed.

See https://github.com/Eeems/oxide/issues/136 and https://github.com/toltec-dev/toltec/issues/9

Toltec has not yet packaged remarkable-stylus which is required for the lamy pen.

**Comment by ademasi** [comment]
I always had the ddvk-hacks and the qt plugin installed.

On first launch, I let systemd handle it, after I use remux if I need to switch between applications.

Even remux was not properly starting xochitl with the good argument before I modified the wrapper file. I don't understand how its possible since remux read the systemd file directly.

So in the future, I can just install the hack and the remarkable-stylus packages to get the Lamy pen working ?

**Comment by Eeems** [comment]
> Even remux was not properly starting xochitl with the good argument before I modified the wrapper file. I don't understand how its possible since remux read the systemd file directly.

@raisjn has a theory on this I believe.

As for Draft and Oxide, they are using configuration in the xochitl package: https://github.com/toltec-dev/toltec/blob/testing/package/xochitl/xochitl.oxide and https://github.com/toltec-dev/toltec/blob/testing/package/xochitl/xochitl.draft

> So in the future, I can just install the hack and the remarkable-stylus packages to get the Lamy pen working ?

That's the plan.

For now what you can do is add a systemd environment override to set the following:
```ini
Environment="QT_QPA_GENERIC_PLUGINS=evdevlamy"
```
Or modify xochitl.draft to add the arguments if using Draft.
Or add the environment variable to xochitl.oxide if you are using Oxide (https://github.com/Eeems/oxide/wiki/Developing-Applications-for-Oxide#properties).

**Comment by danshick** [comment]
I think it is worth noting that systemd unit overrides are "cumulative", so you can create multiple overrides that will all be considered when launching the unit. The term is a "drop-in" if you want to search the docs.

https://www.freedesktop.org/software/systemd/man/systemd.unit.html

> Along with a unit file foo.service, a "drop-in" directory foo.service.d/ may exist. All files with the suffix ".conf" from this directory will be parsed after the unit file itself is parsed. This is useful to alter or add configuration settings for a unit, without having to modify unit files.

**Comment by matteodelabre** [comment]
Closing this. The next step for us is to package the Lamy plugin (already tracked in #9); in the meantime, users can refer to the workarounds above.
