### ISSUE TITLE
calculator segfaults on 2.7

### ISSUE THREAD

**Issue by rbowen** [matteodelabre/toltec#360]
Context: Running 2.7 (updated this morning) on an RM2. I've never installed any third-party anything on this device before today.

Installed remux and calculator, and then attempted to launch calculator:

```
May 26 17:57:14 reMarkable remux[2504]: RENDERING calculator
May 26 17:57:14 reMarkable remux[2504]: LAUNCHING APP calculator calculator
May 26 17:57:15 reMarkable remux[2504]: RESETTING MT GESTURES
May 26 17:57:15 reMarkable remux[2504]: CHECKING PROCESS calculator 0
May 26 17:57:15 reMarkable remux[2504]: RENDERING calculator
May 26 17:57:15 reMarkable remux[2504]: LAUNCHING APP calculator calculator
May 26 17:57:15 reMarkable remux[2504]: RESETTING MT GESTURES
May 26 17:57:15 reMarkable remux[2504]: CHECKING PROCESS calculator 1
May 26 17:57:15 reMarkable remux[2504]: calculator IS ALREADY RUNNING, RESUMING
May 26 17:57:15 reMarkable remux[2504]: SENDING 18 TO GROUP -3034 RET 0
May 26 17:57:15 reMarkable remux[2504]: RENDERING calculator
May 26 17:57:15 reMarkable remux[3034]: EPD platform plugin loaded!
May 26 17:57:15 reMarkable remux[3034]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
May 26 17:57:15 reMarkable remux[3034]: Creating window
May 26 17:57:15 reMarkable remux[3034]: virtual void EPRenderContext::renderNextFrame(QSGRenderer*, uint) can't render without a renderer
```

Running directly from cli gives:

```
EPD platform plugin loaded!
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Creating window
virtual void EPRenderContext::renderNextFrame(QSGRenderer*, uint) can't render without a renderer
Segmentation fault
```

(ie, same output, plus the segfault line.)

Please let me know if I can provide any other details.

**Comment by matteodelabre** [comment]
Hi @rbowen, thanks for your report! I believe this is expected behavior, see #322. Most packages using the Qt framework will not work on ⩾2.6 unless they are compiled with the v2 branch of our toolchain. Some work towards migrating our packages to use toolchain v2 has been done on the [`support-2.6` branch](https://github.com/toltec-dev/toltec/tree/package/support-2.6), but it needs more testing before I can make it into a PR.

**Comment by Eeems** [comment]
Ah right, I had forgotten that we hadn't pushed any of that into testing yet. We probably should do that soon as 2.7 is now out.

**Comment by rbowen** [comment]
Ok, thank you for the confirmation and for the swift response. I'll wait a few weeks and try again, then, should I?
