### ISSUE TITLE
Missing Packages.gz in testing branch

### ISSUE THREAD

**Issue by StefaanVanDooren** [matteodelabre/toltec#367]
opkg update 
Downloading https://bin.entware.net/armv7sf-k3.2/Packages.gz
wget: note: TLS certificate validation not implemented
Updated list of available packages in /opt/var/opkg-lists/entware
Downloading https://toltec-dev.org/testing/Packages.gz
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 404 Not Found
*** Failed to download the package list from https://toltec-dev.org/testing/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://toltec-dev.org/testing/Packages.gz, wget returned 1.

**Comment by LinusCDE** [comment]
Hi,
this is a still ongoing transition problem. We added multiple architectures on testing, changing the path `https://toltec-dev.org/testing` to:
- `https://toltec-dev.org/testing/rmall`
- `https://toltec-dev.org/testing/rm1`
- `https://toltec-dev.org/testing/rm2`

and adding the appropriate ones as well as the new architectures to `/opt/etc/opkg.conf`.

Please try running the [bootstrap script from testing](https://github.com/toltec-dev/toltec/blob/testing/scripts/bootstrap/bootstrap) and running this with the env `toltect_branch=testing`. It should do the migration for you. This command should do that:

```shell
wget -qO- https://raw.githubusercontent.com/toltec-dev/toltec/testing/scripts/bootstrap/bootstrap | toltec_branch=testing bash
```

**Comment by StefaanVanDooren** [comment]
`wget -qO- https://raw.githubusercontent.com/toltec-dev/toltec/testing/scripts/bootstrap/bootstrap | toltec_branch=testing bash`

wget: note: TLS certificate validation not implemented
INFO:  Toltec is already installed
INFO:  To re-enable Toltec after a system upgrade, run 'toltecctl enable'
INFO:  To reinstall Toltec, run 'toltecctl uninstall' first

 `toltecctl uninstall`

-sh: toltecctl: command not found

**Comment by LinusCDE** [comment]
If `toltecctl` doesn't work after a re-login to ssh, try `./local/bin/toltecctl`. Otherwise try to install the package `toltec-bootstrap`.

**Comment by StefaanVanDooren** [comment]
still no luck. I suppose you meant `.local/bin/toltecctl` ? toltec-bootstrap is allready installed and the latest version. I even removed toltec-bootstrap and reinstalled it `opkg remove toltec-bootstrap`

`Package toltec-bootstrap (0.0.1-3) installed in root is up to date.`

**Comment by LinusCDE** [comment]
This version probably doesn't include the toltecctl tool. The latest version should be `0.0.6-1`.

**Comment by LinusCDE** [comment]
[toltec-bootstrap_0.0.1-3_armv7-3.2.ipk.zip](https://github.com/toltec-dev/toltec/files/6616386/toltec-bootstrap_0.0.1-3_armv7-3.2.ipk.zip) here is the build of that file. You can install that manually.

**Comment by LinusCDE** [comment]
Ups. Wrong file. This is from testing: 
[toltec-bootstrap_0.0.6-1_rmall.ipk.zip](https://github.com/toltec-dev/toltec/files/6616401/toltec-bootstrap_0.0.6-1_rmall.ipk.zip)

**Comment by StefaanVanDooren** [comment]
I must be doing something wrong....

`
opkg install toltec-bootstrap_0.0.6-1_rmall.ipk
`

`Unknown package 'toltec-bootstrap'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for toltec-bootstrap found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package toltec-bootstrap.
`

**Comment by LinusCDE** [comment]
Oh. The bootstrap didn't apparently migrate the installation for the new architectures. Add the following line to `/opt/etc/opkg.conf` and it should work:
```
arch rmall 200
```

**Comment by matteodelabre** [comment]
> `wget -qO- https://raw.githubusercontent.com/toltec-dev/toltec/testing/scripts/bootstrap/bootstrap | toltec_branch=testing bash`
> 
> wget: note: TLS certificate validation not implemented
> INFO: Toltec is already installed
> INFO: To re-enable Toltec after a system upgrade, run 'toltecctl enable'
> INFO: To reinstall Toltec, run 'toltecctl uninstall' first
> 
> `toltecctl uninstall`
> 
> -sh: toltecctl: command not found

We recently changed the bootstrap script so that it refuses to run over existing installs. This is to prevent potential data loss since the bootstrap script could otherwise overwrite existing files (#332). Previously, the script could be used over an existing install and would upgrade its configuration. The new way is either to manually update the configuration (as @LinusCDE suggested above), or to uninstall and reinstall Toltec (as the script is suggesting–however, the `toltecctl` command is not yet available on the stable branch, so that won’t work).

**Comment by matteodelabre** [comment]
> Oh. The bootstrap didn't apparently migrate the installation for the new architectures. Add the following line to `/opt/etc/opkg.conf` and it should work:
> 
> ```
> arch rmall 200
> ```

This will work as a temporary solution if you’re just looking to upgrade `toltec-bootstrap` to have access to `toltecctl uninstall` and wish to go the uninstall & reinstall route. If you want to keep your existing install, you’ll need additional lines in your `opkg.conf`. See this answer: https://github.com/toltec-dev/toltec/issues/341#issuecomment-819517368.

**Comment by StefaanVanDooren** [comment]
Oké, thank you both for the assistence. Adding `arch rmall 200` , uninstalling and re-instaling solved my problem.
