### ISSUE TITLE
Installation not working / Invalid checksum for the local wget binary

### ISSUE THREAD

**Issue by clemmrich** [matteodelabre/toltec#368]
When trying to install, I get the following error messages:

root@reMarkable:~# echo "46f556b06f5624b48e974ae040b6213828eff6aa2cc78618a4d8961a27cdc8b3  bootstrap" | sha256sum -c && bash bootstrap
bootstrap: OK
INFO:  Fetching secure wget
ERROR: Invalid checksum for the local wget binary
ERROR: Unexpected error on line bootstrap:105 in function wget-bootstrap
ERROR: This script failed to install. If you can't solve the above
       issue yourself, please report it at:

          https://github.com/toltec-dev/toltec/issues

       (Please also include these error logs to help solving the
       problem faster. Thank you!)

**Comment by matteodelabre** [comment]
Hi @clemmrich, thanks for the report. Did you try running the bootstrap again, just in case this was a one-time network error?

**Comment by clemmrich** [comment]
Yes, I tried it 3 times...

**Comment by matteodelabre** [comment]
Can you please try to download the wget binary manually to see if this is an issue with the bootstrap script or with the network?

```console
$ wget https://toltec-dev.org/thirdparty/bin/wget-v1.21.1
$ sha256sum wget-v1.21.1
```

If this works, what checksum does the last command report? It should be `8798fcdabbe560722a02f95b30385926e4452e2c98c15c2c217583eaa0db30fc`. If it doesn’t match, can you inspect the type of the downloaded file by running the `file wget-v1.21.1` command? The file type should start with `ELF 32-bit LSB executable`.

**Comment by clemmrich** [comment]
Manual download is ok, sha256sum does match. 
The bootstrap script does not seem to dwonload anything, the error message is displayed almost instantly without a delay for a download…

 

 

Von: Mattéo Delabre ***@***.***> 
Gesendet: Freitag, 18. Juni 2021 12:07
An: toltec-dev/toltec ***@***.***>
Cc: clemmrich ***@***.***>; Mention ***@***.***>
Betreff: Re: [toltec-dev/toltec] Installation not working / Invalid checksum for the local wget binary (#368)

 

Can you please try to download the wget binary manually to see if this is an issue with the bootstrap script or with the network?

$ wget https://toltec-dev.org/thirdparty/bin/wget-v1.21.1
 
$ sha256sum wget-v1.21.1

If this works, what checksum does the last command report? It should be 8798fcdabbe560722a02f95b30385926e4452e2c98c15c2c217583eaa0db30fc. If it doesn’t match, can you inspect the type of the downloaded file by running the file wget-v1.21.1 command? The file type should start with ELF 32-bit LSB executable.

**Comment by clemmrich** [comment]
Manual download is ok, sha256sum does match. 
The bootstrap script does not seem to dwonload anything, the error message is displayed almost instantly without a delay for a download…

**Comment by matteodelabre** [comment]
Do you have a pre-existing file at `/home/root/.local/bin/wget`? The bootstrap script assumes that there’s nothing at this location, so that might be the issue if it’s the case.

**Comment by clemmrich** [comment]
there is a file toltecctl in this directory. Should I try to delete it?

**Comment by matteodelabre** [comment]
No, as far as I can tell, only having a file called `wget` could cause this kind of issue.

It would be interesting if we could inspect the file that makes the bootstrap script error out because of its invalid checksum. The script automatically deletes that file upon exit, though. To circumvent this, could you please remove line 324 of the script (the one that reads `trap cleanup EXIT`) and try to run it again? Afterwards, you should be able to access the problematic file at `/home/root/.local/bin/wget`. If it is there, can you please run the `sha256sum` and `file` tests I described above on it?

**Comment by clemmrich** [comment]
there is an executable  file wget, but it's only 0 bytes!

**Comment by matteodelabre** [comment]
Do you have the `/home/root/.local/bin` folder in your `$PATH` before the `/usr/bin` folder, by any chance?

**Comment by clemmrich** [comment]
Indeed - however that happened,

**Comment by clemmrich** [comment]
There is a .bashrc reading:

# Added by Toltec bootstrap (do not modify!)
PATH="/opt/bin:/opt/sbin:/home/root/.local/bin:$PATH"
# End of Toltec bootstrap additions

**Comment by matteodelabre** [comment]
Maybe you installed Toltec using the bootstrap script in `testing` at some point in the past?

**Comment by matteodelabre** [comment]
You can safely remove those lines from your `.bashrc` before restarting your SSH session and re-running the stable bootstrap script.

**Comment by clemmrich** [comment]
Yes, I tried to install tesTing a while ago, but it failed. Later, there was a software update to 2.7 and no obviois trace of the previous toltec install visible...

I removed the lines from bashrc and now install seems to work. Thank you very much!

**Comment by matteodelabre** [comment]
Thank you for your help in figuring out the issue! I created a PR to make the bootstrap script less sensitive to the user’s PATH, so that similar issues won’t happen again (#369).

**Comment by clemmrich** [comment]
Thank you for the excellent support!

 

Von: Mattéo Delabre ***@***.***> 
Gesendet: Freitag, 18. Juni 2021 14:08
An: toltec-dev/toltec ***@***.***>
Cc: clemmrich ***@***.***>; State change ***@***.***>
Betreff: Re: [toltec-dev/toltec] Installation not working / Invalid checksum for the local wget binary (#368)

 

Thank you for your help in figuring out the issue! I created a PR to make the bootstrap script less sensitive to the user’s PATH, so that similar issues won’t happen again (#369 <https://github.com/toltec-dev/toltec/pull/369> ).
