### ISSUE TITLE
Apps not working in testing branch

### ISSUE THREAD

**Issue by clemmrich** [matteodelabre/toltec#374]
The following apps do not work in the testing branch on a Remarkable 2 with version  2.8.0.98 (I do not know wether they are supposed to work already, so simply ignore if known issues): 
- fingerterm (root@reMarkbale prompt is shown, but no keyboard)
- calculator (empty screen)
- wikipedia (empty screen)
- keywriter (empty screen)
- retris (empty screen)

**Comment by matteodelabre** [comment]
Hi @clemmrich, thanks for the report. This is expected, and we’re working to fix this as soon as possible. Please see #322 and #366 for more details.

**Comment by LinusCDE** [comment]
I just got the update to 2.8.0.98 and weirdly enough it worked for me. QT Based apps are still broken, but retris works (it doesn't use QT, just needs a working rm2fb-client/server).

**Comment by matteodelabre** [comment]
Yup! To clarify, not all apps are affected by this, only apps linked to Qt libs, libcrypto, and some other libs (see #322 for details).

**Comment by clemmrich** [comment]
Just FYI: retris is working now for me as well. I started it using remux, which I uninstalled and reinstalled in the meanwhile, so maybe the problem was related to remux, not to retris...
