### ISSUE TITLE
Question: Is there any way to access to Libgen or Sci-Hub libraries with Toltec?

### ISSUE THREAD

**Issue by Sami32** [matteodelabre/toltec#381]
Any advises are welcome.

**Comment by matteodelabre** [comment]
Hi @Sami32. As of today, there is no application packaged in Toltec that provides access to Libgen or Sci-Hub. For accessing Z-Library, [`zshelf`](https://github.com/khanhas/zshelf) is available in Toltec. Note that the issues tab is more aimed at bug reports and feature suggestions. For questions like yours, the discussions tab or the Discord server are more suited.

**Comment by Sami32** [comment]
Thanks, no Discord here.
I just see that you already have a light browser in the work so i guess that should do the job.
