### ISSUE TITLE
toltecctl switch-branch [stable|testing] command not functional on 2.8 firmware

### ISSUE THREAD

**Issue by ZanzyTHEbar** [matteodelabre/toltec#390]
I have tried everything i can, i am probably doing it wrong. I tried to go into the /opt/etc/opkg.conf 
directory to switch toltec-dev.org/stable to /testing - that gave me an error. So then i went onto this github and found the command "toltecctl switch-branch [stable|testing]". Which would be great, i thought, so i reverted the conf and tried that - to no avail. I get a command not found error - so - I am stumped. I am trying to move to the testing repo as i have a rm2 on 2.8, and require the rm2fb version from there. 

Any suggestions?

**Comment by matteodelabre** [comment]
Hello @ZanzyTHEbar. For now, please refer to the following comment for instructions for switching to the testing branch: https://github.com/toltec-dev/toltec/issues/341#issuecomment-819517368. `toltecctl` is not yet available on the stable branch, but we're working to make it available soon.

**Comment by ZanzyTHEbar** [comment]
Thank you, so i updated my package config re the comment you linked - toltecctl is still not available. Is this normal? Is this all i need to continue on installing rm2fb?

**Comment by matteodelabre** [comment]
Did you run `opkg update && opkg upgrade`?

**Comment by matteodelabre** [comment]
@ZanzyTHEbar Any updates?

**Comment by ZanzyTHEbar** [comment]
Yes, i ran both of them - no updates. toltecctl is still not working, and opkg can't find rm2fb anymore. Says it doesn't exist.

**Comment by matteodelabre** [comment]
> toltecctl is still not working

Maybe you’re having a PATH issue. Does `/home/root/.local/bin/toltecctl` exist?

> opkg can't find rm2fb anymore. Says it doesn't exist.

The `rm2fb` package was renamed and split into two packages: `display` (for the server part) and `rm2fb-client` (for the client part). Try using those names instead of `rm2fb`.

**Comment by matteodelabre** [comment]
@ZanzyTHEbar Did you manage to solve your issue?

**Comment by Eeems** [comment]
@ZanzyTHEbar poke again. Is this resolved?

**Comment by matteodelabre** [comment]
Closing this. @ZanzyTHEbar please reopen if you’re still having this issue.
