### ISSUE TITLE
reMarkable 2: toltec: 96 in function wget-bootstrap

### ISSUE THREAD

**Issue by gglex** [matteodelabre/toltec#407]
Hi guys. 

When trying to install Toltec via PuTTY, an error occurs:

           reMarkable: ~/ wget http://toltec-dev.org/bootstrap
           wget: bad address 'toltec-dev.org'
           reMarkable: ~/ echo "9195122984700c76ccdc58e25d09d0fca486324e8fc55ba781f6e1b812cc186c  bootstrap" | sha256sum -c
           bootstrap: OK
           reMarkable: ~/ bash bootstrap
           INFO:  Fetching secure wget
           ERROR: Unexpected error on line bootstrap:96 in function wget-bootstrap
           ERROR: This script failed to install. If you can't solve the above
       issue yourself, please report it at:

           <https://github.com/toltec-dev/toltec/issues>

       (Please also include these error logs to help solving the
       problem faster. Thank you!)
           bootstrap: line 60: clean-path: command not found

How to fix?

Software: ver. 2.8.0.98-patch_23.2.02-0-gd889977

**Comment by matteodelabre** [comment]
Hi @gglex, it seems that you don’t have Internet access. Please make sure that you are connected to Wi-Fi and try again.

**Comment by matteodelabre** [comment]
I just connected the dots and realized that you also posted this on the community Discord :) So I guess we can close this issue? To briefly sum up, this was an issue with the network configuration.

**Comment by gglex** [comment]
Yes you are right. The reason was the virtual DNS, VPN and subnet settings. The case is closed. )))
