### ISSUE TITLE
bootstrap can overwrite existing installs when run after a system upgrade

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#409]
The `bootstrap` script is supposed to halt if it detects an existing Toltec install, to avoid any data loss. [The current implementation](https://github.com/toltec-dev/toltec/blob/ad682b5c60fd6467e26e7c50157626386ab8d050/scripts/bootstrap/bootstrap#L72) only checks if there’s a non-empty `/opt` folder. However, after upgrading the system, the `/opt` folder is no longer mounted even though the install still exists in `/home/root/.entware`. So if one runs the `bootstrap` script right after upgrading, it may overwrite their existing install.

**Comment by LinusCDE** [comment]
Good catch! I think that just checking `/home/root/.entware` instead of `/opt` should be a quick fix. The recommended toltecctl should work as suggested and fix it then.
