### ISSUE TITLE
Enabling after system update after newest toltec update?

### ISSUE THREAD

**Issue by nullstalgia** [matteodelabre/toltec#414]
![image](https://user-images.githubusercontent.com/20761757/129624635-00a70273-6ab7-441e-8f56-c9f1030fed9b.png)

Missing here

**Comment by Eeems** [comment]
@nullstalgia Is this from the text in the release?

**Comment by Eeems** [comment]
Fixed

**Comment by matteodelabre** [comment]
Thanks @nullstalgia for catching this and @Eeems for fixing it! I wonder what happened though? Maybe the backticks got interpreted as shell command substitutions [here](https://github.com/toltec-dev/toltec/blob/2021-W30-6/.github/workflows/stable.yml#L35), but this is only a guess.
