### ISSUE TITLE
Uninstall misses "toltec-wrapper.conf" - causes failed boot

### ISSUE THREAD

**Issue by rmuser2** [matteodelabre/toltec#415]
Hi all,

I am not experienced enough to go into much detail here, but as per the issue linked below, uninstalling toltec missed the toltec-wrapper.conf which caused my RM2 (running 2.9) to get stuck on "remarkable is starting"

https://github.com/ddvk/remarkable2-framebuffer/issues/70

Nathaniel van Diepen (Eeems) got me out of hot water with this, and my RM2 is working again. Thanks you Nathaniel!

**Comment by matteodelabre** [comment]
@rmuser2 Thanks for the report! Do you still have logs from when you did `toltecctl uninstall`? That would be helpful.

**Comment by rmuser2** [comment]
I am afraid that I don't. 

What I did do, to try and rule myself out of the equation, was to install Toltec again, along with the RM2FB and Display packages. 

I then ran the toltecctl uninstall and this time, it rebooted just fine. My guess is that something else I did caused it but the initial toltecctl uninstall did not look wrong, it seemed to run through what it needed to, yet the toltec-wrapper.conf got left behind.

I am not too experienced with this, but I was just trying to get Plato working to try it out. Is this possible right now with 2.9?

**Comment by matteodelabre** [comment]
> I am afraid that I don't.
> 
> What I did do, to try and rule myself out of the equation, was to install Toltec again, along with the RM2FB and Display packages.
> 
> I then ran the toltecctl uninstall and this time, it rebooted just fine. My guess is that something else I did caused it but the initial toltecctl uninstall did not look wrong, it seemed to run through what it needed to, yet the toltec-wrapper.conf got left behind.

Unfortunately, I’ve tried installing and uninstalling Toltec several times on 2.9 and I have not managed to reproduce your issue.

> I am not too experienced with this, but I was just trying to get Plato working to try it out. Is this possible right now with 2.9?

It is, but the rm2fb version currently in stable does not support 2.8. You can switch to the testing branch to try out the next version, which supports version 2.9.0.210: `toltecctl switch-branch testing`, then `opkg upgrade`.

**Comment by matteodelabre** [comment]
Closing this. Please reopen if anyone manages to reproduce the issue and give more information.
