### ISSUE TITLE
RM2: Stuck at start screen

### ISSUE THREAD

**Issue by deanhuff** [matteodelabre/toltec#418]
I just got this device.  I don't even have a stylus yet.  I've managed to get it stuck on "reMarkable is starting"

Here's the commands I've done:

I setup ssh
installed my passwordless ssh key
Backed up /home/root/.local/share/remarkable/xochitl to my PC
Installed toltec
opkg install keywriter
`reMarkable: ~/ opkg install keywriter
Installing keywriter (0.1.0-3) to root...
Downloading https://toltec-dev.org/stable/rmall/keywriter_0.1.0-3_rmall.ipk
Installing rm2fb-client (1.0.1-7) to root...
Downloading https://toltec-dev.org/stable/rm2/rm2fb-client_1.0.1-7_rm2.ipk
Installing xochitl (0.0.0-7) to root...
Downloading https://toltec-dev.org/stable/rmall/xochitl_0.0.0-7_rmall.ipk
Installing display (1.0.1-7) to root...
Downloading https://toltec-dev.org/stable/rm2/display_1.0.1-7_rm2.ipk
Configuring xochitl.
Configuring display.
Created symlink /etc/systemd/system/multi-user.target.wants/rm2fb.service → /lib/systemd/system/rm2fb.service.
Created symlink /etc/systemd/system/xochitl.service.wants/rm2fb.service → /lib/systemd/system/rm2fb.service.
Configuring rm2fb-client.
Configuring keywriter.
Created /home/root/edit for storing your Markdown files
`
ran keywriter
`reMarkable: ~/ keywriter 
EPD platform plugin loaded!
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qrc:/main.qml:114:5: QML Rectangle: Cannot anchor a vertical edge to a horizontal edge.
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
Creating window
qrc:/main.qml:240:44: Unable to assign QString to QQuickAnchorLine
qrc:/main.qml:240:22: Unable to assign QString to QQuickAnchorLine
Framebuffer has wrong id: "mxcfb"
Framebuffer initialized: QImage(QSize(1404, 1872),format=QImage::Format_RGB16,depth=16,devicePixelRatio=1,bytesPerLine=2808,sizeInBytes=5256576) 5256576
^C
`
Screen is unresponsive
Attempted killall xochitl
again ran keywriter
`eMarkable: ~/ keywriter 
EPD platform plugin loaded!
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qrc:/main.qml:114:5: QML Rectangle: Cannot anchor a vertical edge to a horizontal edge.
XMLHttpRequest: Using GET on a local file is dangerous and will be disabled by default in a future Qt version.Set QML_XHR_ALLOW_FILE_READ to 1 if you wish to continue using this feature.
Creating window
qrc:/main.qml:240:44: Unable to assign QString to QQuickAnchorLine
qrc:/main.qml:240:22: Unable to assign QString to QQuickAnchorLine
Framebuffer has wrong id: "mxcfb"
Framebuffer initialized: QImage(QSize(1404, 1872),format=QImage::Format_RGB16,depth=16,devicePixelRatio=1,bytesPerLine=2808,sizeInBytes=5256576) 5256576
^C
`
issued reboot

Stuck on 'reMarkable is starting'

**Comment by deanhuff** [comment]
i can ssh via the usb cable to 10.11.99.1.  what commands can i run to try and get the sceen back?

**Comment by MechEng70** [comment]
Disable tarnish or the other launchers. Then start xochitl. 

systemctl start xochitl

If you killall xochitl then there is no launcher.

**Comment by deanhuff** [comment]
even after a reboot the service doesn't start?

i attempted to start xochitl, it fails:
```
Aug 24 04:15:47 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mxochitl.service: Start
 request repeated too quickly.[[0m
Aug 24 04:15:47 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mxochitl.service: Faile
d with result 'exit-code'.[[0m
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit xochitl.service has entered the 'failed' state with result 'exit-code'.
Aug 24 04:15:47 reMarkable systemd[1]: [[0;1;31m[[0;1;39m[[0;1;31mFailed to start reMarkable main ap
plication.[[0m
-- Subject: A start job for unit xochitl.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit xochitl.service has finished with a failure.
-- 
-- The job identifier is 666 and the job result is failed.
Aug 24 04:15:47 reMarkable crashuploader[182]: All files uploaded
Aug 24 04:15:47 reMarkable xochitl[282]: BIN FILE: /usr/bin/xochitl
Aug 24 04:15:47 reMarkable xochitl[282]: COULDNT LOCATE SIGNATURE IN /usr/bin/xochitl
Aug 24 04:15:47 reMarkable xochitl[282]: PLEASE SEE https://github.com/ddvk/remarkable2-framebuffer/
issues/18
Aug 24 04:15:47 reMarkable xochitl[282]: STARTING RM2FB
Aug 24 04:15:47 reMarkable systemd[1]: rm2fb.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit rm2fb.service has successfully entered the 'dead' state.

```

**Comment by MechEng70** [comment]
I would uninstall everything you installed prior to the crash?

**Comment by deanhuff** [comment]
i unistalled keywriter.  with "opkg remove keywriter"

i have no routable network so i can't opkg update or opkg upgrade.  That line about remarkable2-framebuffer issue 18 has other people with errors...at the bottom it says something about addresses being added for latest firmware (i think?).  I think maybe if i can raise the routable network i can just update and maybe it will be fixed?

any ideas on how to get wlan0 to connect dhcp?

**Comment by MechEng70** [comment]
Should be a typical Linux command.  I know that this isn't a full install but first type 

ifconfig wlan0
If that works then the following may work. 

iwconfig wlan0 essid name key password

name is your ssid name
password is well the password

**Comment by deanhuff** [comment]
I got it to start...i downloaded the .so files from latest release of https://github.com/ddvk/remarkable2-framebuffer/releases/tag/v0.0.7

next I copied the files to my rm via usb ssh addy

then i replaced existing /opt/lib/librm2fb_client.so.1.0.1 and /opt/lib/librm2fb_server.so.1.0.1 with the files i downloaded and boom, works!

it looks like that fix for 0.0.7 was just applied today.

**Comment by MechEng70** [comment]
Good to hear.

**Comment by deanhuff** [comment]
closing out.
