### ISSUE TITLE
Connection to toltec-dev.org being automatically promoted to HTTPS

### ISSUE THREAD

**Issue by sternj** [matteodelabre/toltec#424]
It seems like even a connection on port 80 is unconditionally upgraded to an https connection on port 443-- I think that there's a mix up in your webserver!

Attached is a log; version of remarkable is 2.9.1.217. Please let me know if you need any further information!
```
reMarkable: ~/ wget http://toltec-dev.org/bootstrap
Connecting to toltec-dev.org (172.104.246.107:80)
Connecting to toltec-dev.org (172.104.246.107:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
```

**Comment by matteodelabre** [comment]
Thanks @sternj for the report. I added an exception to the redirect for this URL.

**Comment by sternj** [comment]
This is also happening for http://toltec.delab.re/stable/Packages.gz

**Comment by matteodelabre** [comment]
This should not be an issue since the bootstrap script uses a standalone version of wget that supports TLS to fetch that file.
