### ISSUE TITLE
clean-path

### ISSUE THREAD

**Issue by francescodifilippo** [matteodelabre/toltec#426]
INFO:  Fetching secure wget
ERROR: Unexpected error on line bootstrap:96 in function wget-bootstrap
ERROR: This script failed to install. If you can't solve the above
       issue yourself, please report it at:

           <https://github.com/toltec-dev/toltec/issues>

       (Please also include these error logs to help solving the
       problem faster. Thank you!)
bootstrap: line 60: clean-path: command not found

**Comment by matteodelabre** [comment]
Please see #422.
