### ISSUE TITLE
Error on line 60:

### ISSUE THREAD

**Issue by MN-company** [matteodelabre/toltec#433]
INFO:  Fetching secure wget
ERROR: Unexpected error on line bootstrap:96 in function wget-bootstrap
ERROR: This script failed to install. If you can't solve the above
       issue yourself, please report it at:

           <https://github.com/toltec-dev/toltec/issues>

       (Please also include these error logs to help solving the
       problem faster. Thank you!)
bootstrap: line 60: clean-path: command not found

Can anyone help me plese?

**Comment by Eeems** [comment]
What is the command you are running?

**Comment by MN-company** [comment]
The second: 
echo  "9195122984700c76ccdc58e25d09d0fca486324e8fc55ba781f6e1b812cc186c  bootstrap" | sha256sum -c && bash bootstrap

**Comment by Eeems** [comment]
And what is the first command you ran?

**Comment by matteodelabre** [comment]
Duplicate of #422.
