### ISSUE TITLE
Bricked remarkable 2 after attempting to uninstall toltec

### ISSUE THREAD

**Issue by AntBoss** [matteodelabre/toltec#435]
Hey, i followed his instructions in the link and after i rebooted it is stuck on remarkable is starting. Please help youre my only hope
https://github.com/toltec-dev/toltec/issues/295
Thank you in advance

**Comment by MechEng70** [comment]
Were you installing or uninstalling?
Can you still ssh into the rm2?
Do you have any launchers installed? 

Did you follow the after reboot instructions?

**Comment by AntBoss** [comment]
I was uninstalling, i had downloaded remux but removed it with opkg before following his instructions. I cant ssh into it anymore so i couldnt follow the after reboot instructios. Im currently banging my head against the wall trying to understand how i managed to brick my beloved 400$ device

**Comment by AntBoss** [comment]
It probably has to do with the line about the systemctl. Either xotctl or however it is called is not booting up or i messed up something with the /opt

**Comment by AntBoss** [comment]
I managed to ssh into it

**Comment by AntBoss** [comment]
I FIXED IT
so the problem was with the line systemctl disable opt.mount. All i had to do was ssh into it using a cable and then just enabling it and rebooting it. Thanks for the quick response and have a great day

**Comment by MechEng70** [comment]
That was going to be the next question; HOW are you sshing in the device?  Glad you figured it out.

**Comment by matteodelabre** [comment]
Glad you managed to fix your issue @AntBoss. If other users stumble upon this, please **just run `toltecctl uninstall` to uninstall Toltec**, the instructions you followed on the linked issue were outdated. I updated the linked issue to make this clear.
