### ISSUE TITLE
Include a Toltec-compatible 'koreader.service' unit with installation

### ISSUE THREAD

**Issue by gbyl** [matteodelabre/toltec#437]
### Current Workflow
Toltec is designed to work with a launcher and it does a wonderful job at automatically registering KOReader for use with oxide, remux or draft. That being said, users who would like to simply run KOReader at startup, must do a bit of extra work.

The [default KOReader systemd unit](https://github.com/koreader/koreader/blob/master/platform/remarkable/koreader.service) assumes a manual installation to the home folder, as evidenced by the line:

```vim
ExecStart=/home/root/koreader/koreader.sh
```

The current workflow is to manually change that path to `/opt/bin/koreader` and then copy the unit file to the `/etc/systemd/system` directory.

### Request
It would be ideal if Toltec could automatically create the `/etc/systemd/system/koreader.service` file that already complies with the Toltec directory structure. Leaving it up to the user whether to enable it or not. It would spare beginners some potential confusion and extra work — without interfering with the current function of launchers.

**Comment by Eeems** [comment]
PRs are welcome. That said, I'd recommend that this be a new package that isn't pulled by default for the KOReader package. Instead it be an optional dependency.

**Comment by matteodelabre** [comment]
Regardless of whether this is implemented as a separate package, we should make sure that the systemd unit is declared as conflicting with the launchers so that users don't accidentally end up enabling both at once.

**Comment by matteodelabre** [comment]
@Eeems Could you elaborate on why you believe this should be a separate package?

**Comment by Eeems** [comment]
> @Eeems Could you elaborate on why you believe this should be a separate package?

So people don't get confused with the install instructions telling them how to enable it and get confused as to why KOReader is starting at boot instead of their launcher.

Also, it's not the standard way most users will be using it.

**Comment by gbyl** [comment]
@Eeems I'm afraid I am not familiar enough with Toltec to submit a PR. From the KOReader side of the equation, the best I could do was to provide users with a sed command:
```vim
sed 's|/.*sh|/opt/bin/koreader|' /opt/koreader/koreader.service > /etc/systemd/system/koreader.service
```
It works, but it lacks all the elegance of a Toltec install.

>Also, it's not the standard way most users will be using it.

Although I have encountered a non-negligible minority of people who use their devices primarily for KOReader and without a launcher, I have to agree that it is not the standard. And thus, it probably does not justify creating an entirely separate package for Toltec maintainers to curate and update.

>we should make sure that the systemd unit is declared as conflicting with the launchers so that users don't accidentally end up enabling both at once

@matteodelabre I am not sure this would happen as users who want to use a launcher would not enable KOReader, and users who want to launch KOReader at startup would probably never install a launcher in the first place. That being said, I agree that the deafult systemd unit needs to be either adjusted or declared as conflicting.

**Comment by matteodelabre** [comment]
I understand your point about avoiding user confusion @Eeems, but I’m not convinced having a separate package is the right solution. Instead, I think we should fix existing instructions to make it clear that enabling the service will make KOReader start at boot, and to not do it if they want to keep their launcher. (Also related: #438).

**Comment by gbyl** [comment]
@matteodelabre Thank you for your hard work! I have ran the same tests as you https://github.com/toltec-dev/toltec/pull/441#issuecomment-927385494 and found that if you start from a fresh install then KOReader and Xochitl load at the same time — causing a framebuffer depth mismatch. Please try:

1. `toltecctl uninstall`
2. `bash bootstrap`
3. `exec bash -l`
4. `toltecctl switch-branch testing`
5. `opkg install koreader`
6. `systemctl enable --now koreader`
7. `reboot`

**Comment by Eeems** [comment]
@gbyl I've opened #447, could you confirm if adding `Conflicts=xochitl.service` to `koreader.service` resolves this?

**Comment by matteodelabre** [comment]
It should already conflict with Xochitl because of the `Alias=launcher.service` line. But you need the latest version of the `xochitl` package for that (i.e., you need to `opkg upgrade` after switching branches).

**Comment by gbyl** [comment]
@matteodelabre Excellent! After performing the general upgrade, the prompt now reads:

```
Run the following command(s) to use koreader as your launcher
$ systemctl disable --now xochitl
$ systemctl enable --now koreader
```

@Eeems We probably do not need https://github.com/toltec-dev/toltec/pull/447 anymore as the issue was caused by an oversight of mine.

Thank you both for the outstanding support. Feel free to mark this issue as solved now.

**Comment by gbyl** [comment]
Fixed by https://github.com/toltec-dev/toltec/pull/441
