### ISSUE TITLE
Launchers systemd services: Use alias instead of listing conflicts

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#438]
In order to avoid having more than one launcher application started at boot, the existing launchers each declare a `Conflicts=` relationship with other launchers in their systemd units:

* https://github.com/Eeems/oxide/blob/master/assets/etc/systemd/system/tarnish.service
* https://github.com/toltec-dev/toltec/blob/stable/package/rmkit/remux.service
* https://github.com/toltec-dev/toltec/blob/stable/package/draft/draft.service

This approach works: if several launchers are enabled simultaneously, only one will actually start at boot (although it is not clear which one will start). It is not ideal because each launcher must list all other currently existing launchers in its service unit. If we were to add a new launcher, we’d need to update the service definitions of all other launchers.

I propose we use another mechanism: alias all launcher services to a common name. For example, add `Alias=launcher.service` in the `[Install]` section of each service. This has the effect of making `systemctl enable …` fail if any other launcher is already enabled, and therefore frees us from having to maintain those redundant `Conflicts=` lists. This approach is used on the desktop by display managers (gdm, lxdm, …); they all alias to `display-manager.service`.

Launcher authors (@Eeems @dixonary @raisjn), any thoughts on this? Would you want to have this upstream or only as patches in Toltec? I can open PRs to the respective repos if needed.

**Comment by Eeems** [comment]
I like it. I'll happily accept a PR in my repo as well as here.
