### ISSUE TITLE
Warn users when installing Toltec on an unsupported OS version

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#445]

**Comment by LinusCDE** [comment]
That's a really good idea. How about using remarkable-framebuffers list of versions in a whitelist used for installation as well as reenabling (or downloading it).
If `/etc/version` has no match in this list, we should prevent installtion and reenabling by default and require setting an env to bypass this (e.g. `toltec_ignore_version_error=1`).

**Comment by Eeems** [comment]
Instead of an environment variable to bypass, it might make more sense to just have a `--force` command line argument.

**Comment by LinusCDE** [comment]
That is a good idea, but I think this shouldn't be too easy. If it were `add --force to it`, some users might simply bypass that check and then wonder why the device doesn't reboot properly.

Saying `set the env toltec_ignore_version_error to 1` should rule a good portion of those users preventing them from accidentally bricking their devices.

**Comment by Eeems** [comment]
I think that will only work for a short while, until someone tells someone to just run it with `toltec_ignore_version_error=1` before the command and then everybody will start using it that way.

I think we should just not tell people to use `--force` if the reenable fails, and have a strong warning in the `--help` output.

**Comment by LinusCDE** [comment]
Good point! :+1:

**Comment by dominique-unruh** [comment]
> I think we should just not tell people to use `--force` if the reenable fails, and have a strong warning in the `--help` output.

Maybe it should have a more dangerous name. `--force-and-brick-my-device` or something. I guess most users will then at least check the documentation or Google for it.

**Comment by Eeems** [comment]
The help output would have the documentation required in my proposal. You'll find that having more "dangerous" names doesn't actually keep users from using it without knowing what it actually does. As soon as one person posts a blog post, or reddit comment saying to use it, people will just start using it without reading up on what it does.

**Comment by ZeKap** [comment]
It looks like no one did a PR for it, may I try to make one?

**Comment by Eeems** [comment]
There is a linked PR for this already
