### ISSUE TITLE
Cannot use toltec or opkg

### ISSUE THREAD

**Issue by mioxoim** [matteodelabre/toltec#449]
Since I updated my remarkable I have not been able to access the repository or any of the apps. 

I found this out when I went to update my packages:
`-sh: opkg: command not found`

I went to install toltec as I though it might have disappeared with the update. All the files were there. I follow an old guide how to uninstall as toltecctl unistall was not working either. https://github.com/toltec-dev/toltec/issues/295 

Reinstalling did not solve the issue, I get this when trying to check for the check sum:

```
root@reMarkable:~# bash bootstrap
INFO:  Fetching secure wget
ERROR: Unexpected error on line bootstrap:96 in function wget-bootstrap
ERROR: This script failed to install. If you can't solve the above
       issue yourself, please report it at:
       
           <https://github.com/toltec-dev/toltec/issues>
       
       (Please also include these error logs to help solving the
       problem faster. Thank you!)
bootstrap: line 60: clean-path: command not found
```

**Comment by Eeems** [comment]
`toltecctl reenable`

**Comment by matteodelabre** [comment]
The error you’re seeing upon reinstalling is #422.

**Comment by gbyl** [comment]
@mioxoim Try running:
```
sed -i 's/=https/=http/' bootstrap && bash bootstrap
```

**Comment by mioxoim** [comment]
> The error you’re seeing upon reinstalling is #422.

Thank you that was the solution!
