### ISSUE TITLE
uninstalling toltec

### ISSUE THREAD

**Issue by piforce** [matteodelabre/toltec#470]
After upgrading toltec with 2.10.1.332 as soon as I need the frame buffer the remarkable freezes.  Later I read that version 2.10 isn't supported yet. Fortunatly the usb ssh worked and with:  toltecct1 uninstall , then reboot the device worked again.  Maybe that's an easier way then remarkable2recovery what is on the frontpage.

Toltec installing works but as soon as I install a program the device freezes.

**Comment by piforce** [comment]
When making a rm2fb.conf   in      /opt/etc/rm2fb.conf   toltec works for me

paste:
!20210929140057
version str 2.10.1.332
update addr 0x397ff4
updateType str QRect
create addr 0x39a408
shutdown addr 0x39a3ac
wait addr 0x39992c
getInstance addr 0x38e8dc

**Comment by Eeems** [comment]
>  Maybe that's an easier way then remarkable2recovery what is on the frontpage.

remarkable2-recovery is just for those who aren't able to get into their device anymore. It's a last resort if they are completely stuck.


> When making a rm2fb.conf in /opt/etc/rm2fb.conf toltec works for me
> 
> paste: !20210929140057 version str 2.10.1.332 update addr 0x397ff4 updateType str QRect create addr 0x39a408 shutdown addr 0x39a3ac wait addr 0x39992c getInstance addr 0x38e8dc

Yup, 2.10 support is in the testing branch at the moment.
