### ISSUE TITLE
[feature] figure out how to list packages from remarkable sections 

### ISSUE THREAD

**Issue by raisjnn** [matteodelabre/toltec#5]
we should have a quick way of only listing packages from toltec repo, this is first step towards UI for package management

**Comment by matteodelabre** [comment]
From the device, we can do:

`gunzip -c /opt/var/opkg-lists/toltec | awk '/^Package:/{print $2}'`

to extract a list of packages from the toltec repo.

**Comment by raisjnn** [comment]
#solved
