### ISSUE TITLE
Kernel modules don't support the latest kernel

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#506]
It looks like OS 2.10.3 is now 5.4.70 based. The wireguard and fuse packages generate 4.14.78 and 4.9.84-zero-gravitas folders, but not 5.4.70-zero-gravitas.

cc @jonahweissman @plan5

**Comment by Eeems** [comment]
@matteodelabre we probably should have a kernel meta package along with whatever we do for #445 to support different OS versions.

**Comment by Eeems** [comment]
I wonder if exploring something similar to dkms would make sense?

**Comment by ju6ge** [comment]
Hey is there any information available to help with this? I am trying to use wireguard to connect the remarkable to my home network, but due to the outdated packages it will not work :sob:

**Comment by rM-self-serve** [comment]
still interested

**Comment by Eeems** [comment]
At this point, I think we need to remove the kernel modules from the repository and re-think how we distribute them. Something similar to dkms might be the solution. I think what would be a better solution though would be to package the kernel modules for the various kernel versions, as well as the stock kernel at the different versions, and figure out how to manage picking the right version for the running OS on install/reenable of toltec. A meta package for the OS version, or some other OS version mechanism in the packages is probably needed.

**Comment by Eeems** [comment]
The current plan is to drop kernel module packages for 3.x onward, while keeping the 2.x ones around for now. They'll be automatically removed as part of re-enabling in 3.x. A longer term solution will still be needed to allow people to install modules without having to have a custom kernel with every single one.

I'm tempted to say we have a package that downloads the correct build for your kernel, and have automated builds for every single tag or something? That or maybe a package per kernel tag for the different modules?

The more I think about dkms, the more I think it's a good solution, but that these devices aren't powerful enough for it to be realistic.

**Comment by RomanHargrave** [comment]
> I'm tempted to say we have a package that downloads the correct build for your kernel, and have automated builds for every single tag or something? That or maybe a package per kernel tag for the different modules?

This has likely been solutioned elsewhere, but I ran across this nonetheless while hoping that I could get wireguard working on my rm2 without cross compiling anything myself. 

Has the idea of having one repository for system-software-version-agnostic packages, and then repositories for each supported version of the system software? `opkg` should support this.

**Comment by Eeems** [comment]
> > I'm tempted to say we have a package that downloads the correct build for your kernel, and have automated builds for every single tag or something? That or maybe a package per kernel tag for the different modules?
> 
> This has likely been solutioned elsewhere, but I ran across this nonetheless while hoping that I could get wireguard working on my rm2 without cross compiling anything myself.
> 
> Has the idea of having one repository for system-software-version-agnostic packages, and then repositories for each supported version of the system software? `opkg` should support this.

#701
