### ISSUE TITLE
No xochitl available from oxide

### ISSUE THREAD

**Issue by jgonyea** [matteodelabre/toltec#508]
I'm very new to the side-launching of things on the rm2, so its entirely possible I'm missing something obvious.

rm2, v2.10.3.379
tarnish and oxide are both v2.2.2-1
`cat /etc/version` echos `20211102143141`

I've installed oxide/ tarnish, and I can manually switch to it via ssh commands, but I see no way of launching xochitl from oxide.  I only see two icons in oxide:
* koreader
* Process Manager

How do I add xochitl as a launchable application so I can use the rm2 features, and how then do I switch back to the oxide launcher once inside of xochitl?

**Comment by jgonyea** [comment]
Oops, I posted this to the wrong repository.  Closing issue

**Comment by Eeems** [comment]
Did you install the `xochitl` package? It should have been installed by default.

**Comment by Eeems** [comment]
Also, this is the correct repo for this kind of issue, as the integration between apps is handled by toltec itself.

**Comment by jgonyea** [comment]
I don't recall manually installing it, but attempting to do so produces the following results:
```
reMarkable: /opt/etc/ opkg install xochitl
Package xochitl (0.0.0-10) installed in root is up to date.
```

**Comment by Eeems** [comment]
Interesting. Could you verify that `/opt/usr/share/applications/xochitl.oxide` exists? If not please force reinstall the `xochitl` package.
If it is installed, you'll want to review the tarnish logs to see if it tells you why it's skipping the xochitl application: `journalctl -au tarnish`

**Comment by jgonyea** [comment]
The file existed, but I force reinstalled anyways (v0.0.0-10)

```
reMarkable: ~/ opkg install xochitl --force-reinstall
Removing package xochitl from root...
Reloading Oxide applications: "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
Failed!
Installing xochitl (0.0.0-10) to root...
Downloading https://toltec-dev.org/stable/rmall/xochitl_0.0.0-10_rmall.ipk
Configuring xochitl.
Reloading Oxide applications: Failed!
```
`journalctl -au tarnish` doesn't show anything for this transaction

**Comment by Eeems** [comment]
> `journalctl -au tarnish` doesn't show anything for this transaction

Probably related to the following somehow:

> "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."

Is tarnish running? And when it has been started are there any log lines that mention xochitl?

**Comment by jgonyea** [comment]
Tarnish is running and active.
```
[[0;1;32m●[[0m tarnish.service - oxide system service
     Loaded: loaded (/lib/systemd/system/tarnish.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/tarnish.service.d
             └─rm2fb-preload.conf
     Active: [[0;1;32mactive (running)[[0m since Sun 2021-12-05 07:41:46 UTC; 4min 31s ago
   Main PID: 538 (tarnish)
     CGroup: /system.slice/tarnish.service
             ├─538 /opt/bin/tarnish
             ├─586 /opt/bin/fret
             ├─588 /opt/bin/decay
             ├─596 /opt/bin/oxide
             └─728 sh -c { echo -n > /dev/tcp/192.168.1.1/80; } > /dev/null 2>&1

Dec 05 07:41:58 reMarkable tarnish[538]: Write touch move <Touch 8 (22, 1857) released>
Dec 05 07:41:58 reMarkable tarnish[538]: Write touch up <Touch 8 (22, 1857) released>
Dec 05 07:41:59 reMarkable tarnish[642]: ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
Dec 05 07:41:59 reMarkable tarnish[645]: ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
Dec 05 07:41:59 reMarkable tarnish[646]: ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
Dec 05 07:41:59 reMarkable tarnish[649]: ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
Dec 05 07:41:59 reMarkable tarnish[538]: link failed:
Dec 05 07:42:02 reMarkable tarnish[670]: ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
Dec 05 07:42:02 reMarkable tarnish[673]: ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
Dec 05 07:42:02 reMarkable tarnish[674]: ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
```

**Comment by jgonyea** [comment]
I have nothing of super import on this device, so if I need to wipe it clean and restart from the beginning, I'm happy to do so.

**Comment by Eeems** [comment]
> I have nothing of super import on this device, so if I need to wipe it clean and restart from the beginning, I'm happy to do so.

That probably won't really help. Unless you did something really odd when initially installing.



> Tarnish is running and active.

And the log lines during startup of tarnish? Does it talk about xochitl at all? Are there any messages about things not existing anymore? Ignore the `ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.` lines, they are technically just warnings, not errors.

What does `rot apps get applications` return?

**Comment by jgonyea** [comment]
```
reMarkable: /opt/etc/draft/ rot apps get applications

{
  "KOReader": "/codes/eeems/oxide1/apps/67a9b43a3c265ebfb21ce90997e7b7d3",
  "codes.eeems.corrupt": "/codes/eeems/oxide1/apps/661a3023fc785f5b8d244960d7da0db5",
  "codes.eeems.decay": "/codes/eeems/oxide1/apps/549212b2493354f4a9ee5da097a2dacd",
  "codes.eeems.erode": "/codes/eeems/oxide1/apps/f8c23b4485cf5760b3468cae491a0a72",
  "codes.eeems.fret": "/codes/eeems/oxide1/apps/f3999e4363cb568ea6ccc50aa4b27b23",
  "codes.eeems.oxide": "/codes/eeems/oxide1/apps/d3641f0572435f76bb5cc1468d4fe1db"
}
```
I ran the output though a json prettifier

and no, I don't see anything in the log entries regarding xochitl for tarnish

**Comment by Eeems** [comment]
So it's failing to register for some reason. Could you post the log output of tarnish after restarting it, there should be something there about why it's refusing to load it. Like it being unable to find the executable or something

**Comment by raisjn** [comment]
have you tried reimporting applications from oxides menu? this worked for me

**Comment by Eeems** [comment]
> have you tried reimporting applications from oxides menu? this worked for me

Oxide is using xochitl.oxide as it has required settings that xochitl.draft doesn't provide.

**Comment by jgonyea** [comment]
Reimporting freezes oxide, forcing me to restart it via the ssh session.

How do get all the logs of tarnish starting?.  Running `journalctl -au tarnish` doesn't seem to give me everything.

**Comment by jgonyea** [comment]
Here's the log I found so far:
https://pastebin.com/8a5YwzCf

**Comment by Eeems** [comment]
> How do get all the logs of tarnish starting?.  Running `journalctl -au tarnish` doesn't seem to give me everything.

this would be the correct way, you can use the arrow keys and page up/down to navigate through the logs. You can also add `-f` to have it automatically follow the logs as they are outputted.


> Here's the log I found so far:
> https://pastebin.com/8a5YwzCf

This is getting close, could you provide more? It looks like you got right up to where I would expect it to be parsing the xochitl application information, which would give us what we need to know what is happening.

**Comment by Eeems** [comment]
@jgonyea poke?

**Comment by jgonyea** [comment]
I'm pretty sure the log just stops there, but I'll confirm later this week.  I'm swamped with the $DAYJOB stuff for now.

**Comment by Eeems** [comment]
The log would not stop there, you'll just need to scroll further through it with the arrow keys or page up/down.

**Comment by Eeems** [comment]
@jgonyea any followup?

**Comment by jgonyea** [comment]
Thank your for your patience.

https://pastebin.com/VCBzez3S
Here's some more log entries.

Of possible note, I see the following:
```
Directory", QVariant(QString, "")))
Dec 17 04:02:22 reMarkable tarnish[531]: Registered "/codes/eeems/oxide1/apps/d3641f0572435f76bb5cc146
8d4fe1db" codes.eeems.oxide1.Application
Dec 17 04:02:22 reMarkable tarnish[531]: Invalid file  "/opt/usr/share/applications/xochitl.oxide"
```

**Comment by Eeems** [comment]
What is the content of `/opt/usr/share/applications/xochitl.oxide`?

**Comment by jgonyea** [comment]
```
reMarkable: /opt/usr/share/applications/ cat xochitl.oxide
{
    "displayName": "Xochitl",
    "description": "Read documents and take notes",
    "bin": "/opt/bin/xochitl",
    "icon": "/opt/etc/draft/icons/xochitl.png",
    "flags": ["nosplash", "chroot"],
    "permissions": ["power"],
    "directories": [
        "/dev/shm",
        "/etc",
        "/home/root",
        "/opt/etc",
        "/run/dbus",
        "/run/systemd/resolve",
        "/run/udev",
        "/tmp/runtime-root",
        "/usr/share",
        "/var/cache/fontconfig",
        "/var/lib/dbus",
    ],
    "environment": {
        "QMLSCENE_DEVICE": "epaper",
        "QT_QPA_PLATFORM": "epaper",
        "QT_QPA_EVDEV_TOUCHSCREEN_PARAMETERS": "rotate=180",
        "HOME": "/home/root",
        "XDG_RUNTIME_DIR": "/tmp/runtime-root"
    }
}

```

**Comment by matteodelabre** [comment]
There seems to be an extra comma on line `"/var/lib/dbus"`. @Eeems is the JSON parser in Oxide sensitive to that?

**Comment by jgonyea** [comment]
After removing the comma and restarting tarnish, oxide begins to load, but then xochitl starts immediately afterwards. The app launcher isn't reachable.

**Comment by jgonyea** [comment]
Did an opkg update/upgrade, restarted tarnish, and oxide still only showed the originally noted 2 applications. Used the menu to reimport, which didn't crash the interface this time and now all icons are showing!

**Comment by jgonyea** [comment]
Bugger, nope.  Something is still autostarting up the xochitl application and I can't get back to the oxide application.

**Comment by Eeems** [comment]
Tarnish could be crashing and auto starting xochitl. Check the logs again

**Comment by jgonyea** [comment]
I did another opkg update/upgrade today.  Ran a `systemctl disable --now draft` and `systemctl enable --now tarnish` 

I see oxide start, but soon there after, xochitl starts on its own.

https://pastebin.com/GuU8DxWj

**Comment by Eeems** [comment]
Did you disable xochitl first? It needs to be disabled after an upgrade.

Also do you have xochitl set as your Oxide startup app?

Edit: looking at the logs, it looks like xochitl is being started by oxide. You should double check in the launcher if you have it set as the startup app. Long press on the icon and you should see the button to toggle it's state and what state it is in.

**Comment by jgonyea** [comment]
Sorry I haven't got back to you on this.  I've run out of time to chase this down.  Draft launcher is functional enough for my current needs.  If I need to pursue this again, I'll (re)open a ticket.
