### ISSUE TITLE
Reenable Failure on Packages wget

### ISSUE THREAD

**Issue by Servinjesus1** [matteodelabre/toltec#540]
I am getting a peer reset (alert code 80) on attempting to reenable toltec, after updating from ~2.7 to RM 2.11.0.442.

Specifically, `wget` fails on attempting to download list from `https://toltec-dev.org/stable/rmall/Packages.gz`.

```
reMarkable: ~/ toltecctl reenable
Bind mount configuration for '/opt' already exists, updating
Downloading https://bin.entware.net/armv7sf-k3.2/Packages.gz
wget: note: TLS certificate validation not implemented
Updated list of available packages in /opt/var/opkg-lists/entware
Downloading https://toltec-dev.org/stable/rmall/Packages.gz
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
*** Failed to download the package list from https://toltec-dev.org/stable/rmall/Packages.gz

Downloading https://toltec-dev.org/stable/rm2/Packages.gz
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
*** Failed to download the package list from https://toltec-dev.org/stable/rm2/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://toltec-dev.org/stable/rmall/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://toltec-dev.org/stable/rm2/Packages.gz, wget returned 1.
```

Or, simply the `Package.gz`:

```
reMarkable: ~/ wget https://toltec-dev.org/stable/rmall/Packages.gz
Connecting to toltec-dev.org (172.104.246.107:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
```

Is this akin to #424?

**Comment by matteodelabre** [comment]
Does `/opt/bin/wget` exist on your device? Can you check the result of `command -v wget`? It should return `/opt/bin/wget` but I assume it’s going to give you `/usr/bin/wget`. In that case, can you print the contents of your PATH variable?

**Comment by Servinjesus1** [comment]
You're right, it does execute from `/usr/bin`. Here's what's in my PATH:

```
/opt/bin
/opt/sbin
/home/root/.local/bin
/usr/local/bin
/usr/bin
/bin
/usr/local/sbin
/usr/sbin
/sbin
```

**Comment by matteodelabre** [comment]
I assume you have no `/opt/bin/wget` executable then? Or perhaps it doesn’t have the -x flag?

**Comment by matteodelabre** [comment]
If that’s the case, I assume you don’t have the `wget-ssl` package installed (which is strange in itself, since it comes by default with the standard Toltec install—how old is your install? Did you remove the `wget-ssl` package manually?). To install it back, download it manually from [Entware](https://bin.entware.net/armv7sf-k3.2/wget-ssl_1.21.2-1_armv7-3.2.ipk), `scp` it to your device, and run `opkg install wget-ssl_1.21.2-1_armv7-3.2.ipk`.

**Comment by Servinjesus1** [comment]
`wget-ssl` was what was needed, thanks! Not sure, I've had to reenable it a few times through RM updates, and try to keep everything up to date through `opkg`. If that's not how to update toltec itself, then my install's likely old.
