### ISSUE TITLE
Update keywriter to latest version

### ISSUE THREAD

**Issue by simonante** [matteodelabre/toltec#544]
Would be great to have this rm keywriter fork with smaller font size for edit mode:
https://github.com/danschrage/remarkable-keywriter

There have been few more people who wanted to have a writing experience with smaller font size.

**Comment by Eeems** [comment]
It would probably make more sense to ask for that change to be upstreamed, or configuration added to tweak it per install.

**Comment by matteodelabre** [comment]
Seems to have been added to upstream. Keeping this open as a reminder to update our package.
