### ISSUE TITLE
Check if user has autoupdate turned on

### ISSUE THREAD

**Issue by pbouffard** [matteodelabre/toltec#553]
Not sure if it's exposed somehow in the OS but given that an auto update of the RM2 OS can lead to suddenly losing the ability to use unofficial software, it would be great if on install/update of toltec that it check if the user has auto-update turned on and give a warning or perhaps even turn it off if that's possible.

If not at least a very conspicuous message somewhere in the install flow to direct the user to do this would go a long way.

**Comment by matteodelabre** [comment]
Thanks for the suggestion. I believe auto-updates are enabled if and only if the `update-engine` systemd service is enabled, so it should be possible to check this in a script. We could even suggest the `systemctl mask update-engine` way of permanently disabling auto-updates.

**Comment by matteodelabre** [comment]
Solved by #641.
