### ISSUE TITLE
Support for Remarkable 2 - 2.12.1.527

### ISSUE THREAD

**Issue by sammcj** [matteodelabre/toltec#554]
Remarkable 2 shipped 2.12 last week, the current build being 2.12.1.527.

It would be great to have an update to Toltec to support this.

**Comment by MechEng70** [comment]
Currently in beta. 

I can comment that it is currently functioning.

**Comment by idnovic** [comment]
> Currently in beta.
> 

What does that mean? Is it possible for me to test it or do I need to wait until it is released to stable?

**Comment by MechEng70** [comment]
If you are using the stable releases, then you may have to wait a few days.  
You can always use the testing branch.  

Seems like there is a command now to switch:
`toltecctl switch-branch testing`

**Comment by idnovic** [comment]
> Seems like there is a command now to switch: `toltecctl switch-branch testing`

Thank you. 
I never used toltec before. I will test it out later this week. 

Can you check if you can only update a single package to testing branch?

**Comment by MechEng70** [comment]
It updates all packages in the testing branch.

**Comment by LinusCDE** [comment]
If you want to test only a specific package, the easiest is probably to head to <https://toltec-dev.org/testing/>, download the package in question (Link in last column that gives you can `.ipkg` file), upload this to your rM (Filezilla, WinSCP, ...) and use `opkg install filename.ipkg`.

Please note that this can of course cause dependency problems and may require manual troubleshooting as cherry-picking specific packages from another branch is not expected. But in practice this should work.

If you just need support for the newest firmware, most packages usually work fine as long as the QT Libs don't have breaking changes (which is rare). The one package that usually breaks things on the rM 2 is the display support. This is the package `display` which is the rm2fb-server on the rM 2. This needs to know the exact offsets of some functions per fw revision to work and enable other apps to display anything on the eInk screen at all. Most changes nowadays are updating these offsets. These are usually tracked in [this issue](https://github.com/ddvk/remarkable2-framebuffer/issues/18) and usually contain the newest offsets (or a Link to a PR for it) for brand new firmware. You can manually test them by getting these and putting them in a file called `/opt/etc/rm2fb.conf` and these should apply after a reboot.

Here is a screenshot of how my file current looks (did test some older firmwares with this file):

![grafik](https://user-images.githubusercontent.com/22298664/154343205-ca8984bd-f871-4fb7-bb47-588d4ced160d.png)

The version/date following the exclamation mark should match the content of the file `/etc/version` and the "version str" should the be the firmware version that you can see in the UI.
