### ISSUE TITLE
Rework pre/post scripts

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#60]
I think we should abstract away a bunch of the complexity of the pre/post scripts. Ideally we should have the following scripts that a package can define:

- preinstall
- postinstall
- preremove
- postremove
- preupgrade
- postupgrade

The tooling that builds a package should automatically create the wrapper script that would be required to determine which of these scripts should be run at what time (see https://github.com/toltec-dev/toltec/issues/55#issuecomment-697986350)

**Comment by LinusCDE** [comment]
If I'm not mistaken we already have all scrips aside from the upgrade ones. Those are built into entware package files and basically just copied over. So adding those scripts would in my opinion only increase complexity for everyone.

**Comment by Eeems** [comment]
I fail to see how it would increase complexity. Right now you need to handle an argument to even know what to do. Which we haven't fully documented. I'd much rather have a script that has one input/output state and doesn't have to worry about what the argument being passed in means.

**Comment by LinusCDE** [comment]
That's a good point. For people just submitting packages it would be easier indeed. I mixed up the viewpoints.

**Comment by matteodelabre** [comment]
I think it’s a good idea. I’d go further and suggest that we consolidate all those scripts into a single `configure` script which contains a function for each of those actions. Indeed, it seems to me that as package maintainers, it’s easier if we can see all those scripts at a glance in the same file.

**Comment by Eeems** [comment]
> I think it’s a good idea. I’d go further and suggest that we consolidate all those scripts into a single `configure` script which contains a function for each of those actions. Indeed, it seems to me that as package maintainers, it’s easier if we can see all those scripts at a glance in the same file.

We could probably move it all into the main package file. That way you could use package time variables and just embed them into the resulting scripts.

**Comment by matteodelabre** [comment]
Agreed. When extracting those functions to separate files during the packaging script, we’ll also need to take care to extract the package variables at the top of the recipe.
