### ISSUE TITLE
Explore packaging the kernel

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#61]
Since we can access the kernel and dtb file under `/boot`, we technically could deploy updates to the kernel with opkg. With recovery mode and the second partition, we have options to save the device if something goes wrong.

This will allow us to add modules to the kernel, or to tweak the device tree to allow for things like disabling certain buttons before suspending.

**Comment by Eeems** [comment]
Perhaps instead of the entire kernel we should start looking into packaging smaller kernel modules à la wireguard.

**Comment by matteodelabre** [comment]
This sounds interesting. Maybe we could list here some modules that could be of interest for packaging.

**Comment by Eeems** [comment]
uinput

**Comment by Eeems** [comment]
I'd say that this is implemented.
