### ISSUE TITLE
Is 2.14.3.977 usable?

### ISSUE THREAD

**Issue by palfrey** [matteodelabre/toltec#626]
Website says no, but [remarkable-hacks now has support](https://github.com/ddvk/remarkable-hacks/commit/c3ec0b6aa480baaaaf63460c99796f952265bf19) as does the [rm2 framebuffer](https://github.com/ddvk/remarkable2-framebuffer/pull/104) so not sure?

**Comment by Eeems** [comment]
Not until the packages are updated and make it to stable.

**Comment by palfrey** [comment]
* Display update ~~https://github.com/toltec-dev/toltec/pull/623~~ https://github.com/toltec-dev/toltec/pull/628
* ddvk update https://github.com/toltec-dev/toltec/pull/627

**Comment by palfrey** [comment]
I've installed toltec stable (as the bootstrap didn't use either package), and then built/installed both of these by hand. LGTM on my rm2 running 2.14.3.977

**Comment by Eeems** [comment]
> I've installed toltec stable (as the bootstrap didn't use either package), and then built/installed both of these by hand. LGTM on my rm2 running 2.14.3.977

I would recommend commenting on the pull requests themselves, and testing with the artifacts generated there.

**Comment by sloane-shark** [comment]
@palfrey would you mind putting together a gist or something demonstrating how you got this working on the latest firmware? I’m really interested to try, but unsure when official support will come

**Comment by palfrey** [comment]
> @palfrey would you mind putting together a gist or something demonstrating how you got this working on the latest firmware? I’m really interested to try, but unsure when official support will come

I mostly just did the standard install and then you can copy individual .ipk's (either from local hand-built stuff or the artifacts in the PRs) and install those with `opkg install <file>`

**Comment by atze007** [comment]
> > @palfrey would you mind putting together a gist or something demonstrating how you got this working on the latest firmware? I’m really interested to try, but unsure when official support will come
> 
> I mostly just did the standard install and then you can copy individual .ipk's (either from local hand-built stuff or the artifacts in the PRs) and install those with `opkg install <file>`

I'm sorry if I'm being a bit stupid.... But I would also like to use tolltec and am on 2.14.3.1005. How exactly do I have to proceed or what do I have to install additionally?

**Comment by sloane-shark** [comment]
@atze007 **assuming ddvk and display support that firmware**, you can follow the normal installation procedure, but any framebuffer apps will require you to copy the updated installers for ddvk and display to your remarkable and run them manually.

**Comment by Eeems** [comment]
We don't support running ddvk-hack's installer directly with toltec's package already installed. You'd need to grab the updated ipk artifacts from one of the open pull requests, or switch to the testing branch if the pull request has been merged.

**Comment by palfrey** [comment]
I think https://github.com/toltec-dev/toltec/pull/635 solves this?
