### ISSUE TITLE
Replace recipe metadata variables by associative array

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#64]
Currently, recipes declare a handful of metadata variables such as `pkgname`, `url` and `source` which have more or less generic names. This causes two problems:

* We must take care of not overwriting them inside the build scripts.
* `shellcheck` is not able to automatically detect that those variables are defined, unless we declare them manually.

I propose placing all these variables in a single Bash associative array to solve the above two problems. Here’s an example of how that could look like for plato.

_Before:_

```
pkgname=plato
pkgdesc="Document reader"
url=https://github.com/LinusCDE/plato
pkgver=0.9.1-8
timestamp=2020-09-21T18:40Z
section=readers
maintainer="Linus K. <linus@cosmos-ink.net>"
license=AGPL-3.0-or-later

image=rust:v1.1
source=(https://github.com/LinusCDE/plato/archive/9b18b76769751e7aa760ae3c31ff8dd263911b8d.zip)
sha256sums=(478333e0f32096471950ef3f1f76d7cc42f6802dc417227518b6ffc5593b4457)
```

_After:_

```
declare -A metadata=(
    [name]=plato
    [description]="Document reader"
    [url]=https://github.com/LinusCDE/plato
    [version]=0.9.1-8
    [timestamp]=2020-09-21T18:40Z
    [section]=readers
    [maintainer]="Linus K. <linus@cosmos-ink.net>"
    [license]=AGPL-3.0-or-later

    [image]=rust:v1.1
    [sources]=https://github.com/LinusCDE/plato/archive/9b18b76769751e7aa760ae3c31ff8dd263911b8d.zip
    [sha256sums]=478333e0f32096471950ef3f1f76d7cc42f6802dc417227518b6ffc5593b4457
)
```

Then we can:

* Retrieve a piece of metadata: `${metadata[name]}`
* Check if an attribute is defined: `[[ -v metadata[nonexisting] ]]`
* Define a default value for an attribute: `[[ ! -v metadata[nonexisting] ]] && metadata[nonexisting]="default value"`.

**Comment by Eeems** [comment]
From the perspective of building the tooling I get it. But from the perspective of creating packages I really don't like it.
I'd much rather that the tooling did that behind the scenes for me so that the package was still dead easy to write.

**Comment by matteodelabre** [comment]
I understand your position. Another limitation of this approach is that lists cannot be nested inside associative arrays in Bash, therefore fields like `source` and `depends`, which are lists, will break. Maybe a compromise would be to consistently add a prefix like `pkg…` in front of metadata variables? Then we’d only need to make sure that we don’t use this prefix in our build scripts in order to avoid collisions.
