### ISSUE TITLE
kernelctl install error

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#647]
![image](https://user-images.githubusercontent.com/1176979/201450608-544f361b-9817-4699-816f-3d7f5aaf8317.png)

@Etn40ff

**Comment by Eeems** [comment]
This is using a fresh install

**Comment by Eeems** [comment]
It looks like the following resolves it:
![image](https://user-images.githubusercontent.com/1176979/201450686-6bc5169c-8980-4423-b721-c0600832fbdd.png)

**Comment by Etn40ff** [comment]
I think this is due to the new way in which configure works: `kerneltl list` uses `get_current_kernel_name` which assumes current.tar.bz2 exists. I'll fix it presently.
