### ISSUE TITLE
Installing and uninstalling seemingly not possible

### ISSUE THREAD

**Issue by klettervirus** [matteodelabre/toltec#652]
I tried to install toltec, but obviously did that before some years ago. On my rm1. Software Version 2.7.0.51
The following happens, when I 1) try to install it and 2) try to remove it:

```
╺━┓┏━╸┏━┓┏━┓   ┏━╸┏━┓┏━┓╻ ╻╻╺┳╸┏━┓┏━┓
┏━┛┣╸ ┣┳┛┃ ┃   ┃╺┓┣┳┛┣━┫┃┏┛┃ ┃ ┣━┫┗━┓
┗━╸┗━╸╹┗╸┗━┛   ┗━┛╹┗╸╹ ╹┗┛ ╹ ╹ ╹ ╹┗━┛
reMarkable: ~/ toltecctl uninstall
-sh: toltecctl: command not found
reMarkable: ~/ wget http://toltec-dev.org/bootstrap
Connecting to toltec-dev.org (5.161.99.157:80)
wget: can't open 'bootstrap': File exists

```
Can someone please point me to a way to remove any residue from previous installs so I can get a new clean install? Sorry, my Linux knowledge is only tiny, I can use a command line, but have no idea how to get a handle on this one.
Thank for all the effort and support!

**Comment by matteodelabre** [comment]
I’m moving this to the discussions forum.
