### ISSUE TITLE
Split packages

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#66]
Sometimes several packages can be generated from a single source. For example, harmony, nao, mines, remux and simple all come from the rmkit Git repo. It would make packaging simpler if we could combine the four recipes into a single one, _à la_ [Arch split packages](https://jlk.fjfi.cvut.cz/arch/manpages/man/PKGBUILD.5#PACKAGE_SPLITTING).

**Comment by Eeems** [comment]
This would be good for Oxide as well. I'd like to split out the bundled applications.
