### ISSUE TITLE
Issue with remarkable 1 synchronization after toltec installation

### ISSUE THREAD

**Issue by odisseo79** [matteodelabre/toltec#668]
Dear all,
I do not know if it's the right place to write.
Every time I reenable toltec the remarkable 1 stops syncing with the cloud.
The only way to recover synchronization is performing a firmware update. Indeed, I had to join the beta program in order to have frequent updates and be able to sync again.
Is there anyone who is facing the same issue?
I also wrote to remarkable support but their suggestions were not helpful.
Regards
Odi

**Comment by Eeems** [comment]
What other packages did you install? What OS versions? Can you post some logs? What happened when you tried the check sync button?

**Comment by odisseo79** [comment]
It looks like the problem was related to remux and there is a way to fix it.
I close the issue.
