### ISSUE TITLE
Prevent accidental inclusion of source archive in final packages

### ISSUE THREAD

**Issue by LinusCDE** [matteodelabre/toltec#70]
<img src="https://user-images.githubusercontent.com/22298664/94328900-b429f200-ffb6-11ea-819e-6e826d746896.png" width="50%">

Having the zip file with the source inside of the source directory will be problematic when having binary distributions as they usually just zip the entire src folder and don't realize that their src folder has this file added.

This issue first was found when adding koreader https://github.com/toltec-dev/toltec/pull/44#discussion_r493072741 . It seems to have been forgotten and the zip is currently still included in the [.ipk package](https://toltec.delab.re/testing/koreader_2020.08.01-1_armv7-3.2.ipk) on testing.

We should consider either removing the file or moving it e.g. one level above to the final .ipk file.

**Comment by LinusCDE** [comment]
@raisjnn https://github.com/toltec-dev/toltec/pull/44#discussion_r493072741 still needs to be addressed. But let's see whether we find a universal solution here first.

**Comment by matteodelabre** [comment]
The current behavior matches `makepkg`’s behavior. I’d rather handle this on a package-level basis, for example the KOReader package could simply `rm` the zip file before (or after) moving everything to `$pkgdir`.

**Comment by raisjn** [comment]
> It seems to have been forgotten and the zip is currently still included in the .ipk package on testing.

That's on all of us :-( ![Screenshot_2020-09-26_10-12-03](https://user-images.githubusercontent.com/70462544/94346382-30d1c600-ffe1-11ea-9099-44fb273079dd.png)

Please open a PR with the fix (if you have the time)

**Comment by LinusCDE** [comment]
> > It seems to have been forgotten and the zip is currently still included in the .ipk package on testing.
> 
> That's on all of us :-( ![Screenshot_2020-09-26_10-12-03](https://user-images.githubusercontent.com/70462544/94346382-30d1c600-ffe1-11ea-9099-44fb273079dd.png)
> 
> Please open a PR with the fix (if you have the time)

Yeah. I really missed that. I think that I meant to just approve the attached changed that you found if I'm not mistaken. I didn't really realize that adding the change as "approved" (since you wanted the specific change) would count as a approve of the earlier review as well.

Well, it was still my bad, too. I think I even started the discussion with two topics which wasn't clean either.

I'll add that probably tomorrow.

**Comment by LinusCDE** [comment]
> The current behavior matches `makepkg`’s behavior. I’d rather handle this on a package-level basis, for example the KOReader package could simply `rm` the zip file before (or after) moving everything to `$pkgdir`.

While I don't find that particular useful, I guess that the Arch folks had quite some time to consider this and I respect that we're  conforming to the standard.

We should probably remember though to mention that to future package creators in docs.
