### ISSUE TITLE
yaft package doesn't use terminfo file(s) in `/opt/share/terminfo`

### ISSUE THREAD

**Issue by kiwiz** [matteodelabre/toltec#714]
This leads to TUI programs like `vim` not working properly.

Currently, the files are dropped into `/opt/share/terminfo/y/yaft-256color`. The file should either be copied or symlinked into `/etc/terminfo/y`.

Relevant `yaft` issue: https://github.com/timower/rM2-stuff/issues/15

**Comment by kiwiz** [comment]
Actually, another option is `$HOME/.terminfo/y` - confirmed that this works for `vim`.

**Comment by Eeems** [comment]
To clarify the title (before I adjust it). This is the correct location for these files in toltec. Yaft doesn't respect the `/opt` folder for pulling terminfo, and we should patch it in our package to do so.

**Comment by Eeems** [comment]
We probably should update the package to depend on entware's terminfo as well.

**Comment by Eeems** [comment]
Some initial looking shows that we should be adding a script that imports `/opt/etc/profile` to `/etc/profile.d`
