### ISSUE TITLE
Uninstalling fails

### ISSUE THREAD

**Issue by dermanu** [matteodelabre/toltec#752]
Hi there,

I try to uninstall toltec using `toltecctl uninstall`. However, I got the following message: 
```
This will wipe out all files in '/opt'. Continue? [y/N] y
wget: unrecognized option '--no-verbose'
BusyBox v1.35.0 () multi-call binary.

Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR]
	[--post-data STR | --post-file FILE] [-Y on/off]
	[-P DIR] [-U AGENT] [-T SEC] URL...
Unable to fetch standalone opkg, make sure you have a stable Wi-Fi connection
```

Wifi is connected. The OS version of my remarkable 2 is 3.8.1.1960 (Linux reMarkable 5.4.70-v1.3.4-rm11x #1 SMP PREEMPT Wed Mar 15 06:06:44 UTC 2023 armv7l GNU/Linux). 

It might be due to me forgetting that I had toltec installed and then updating the Remarkable (even enrolling in the beta version... :sweat_smile:).

All the best, 
dermanu

**Comment by Eeems** [comment]
Toltec doesn't support 3.8, so it isn't enabled. You don't need to uninstall it. You can always downgrade to a supported version, re-enable and then uninstall if you really need to, otherwise you can just leave it inits not enabled state.
