### ISSUE TITLE
rmfm crashes if there is a broken symlink

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#765]
@TheLastZombie I'm opening this here since registration is closed on the site hosting rmfm's source code.

**Describe the issue**
Opening rmfm with a broken symlink in your home directory will cause it to crash

**To Reproduce**
N/A

**Expected behaviour**
It should not crash

**Upstream issue**
N/A

**Screenshots**
N/A

**Comment by TheLastZombie** [comment]
Thanks for the report, this has been fixed with [`3b80a077fd`](https://forgejo.sny.sh/sun/rmFM/commit/3b80a077fd6d672f9f00838b0a3762812643d542). I have released a [patch](https://forgejo.sny.sh/sun/rmFM/releases/tag/1.5.1) and updated the package in #766.
