### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by regis7391** [matteodelabre/toltec#844]
I hope I won't be annoying with my question, since I am a beginner at this. 
I tried the installation process and here is what happened

**root@reMarkable:~# echo "37f6cc2a0c87dfe9b895c01a546315e9e43d87b9dc04e39b28e2c76ea87b1f7c  bootstrap" | sha256sum -c && bash bootstrap
bootstrap: OK
INFO:  Fetching secure wget
INFO:  Bootstrapping Opkg
bootstrap: line 119:  1406 Segmentation fault      wget --no-verbose "$entware_remote/opkg" --output-document "$opkg_path"
ERROR: Could not fetch opkg, make sure you have a stable Wi-Fi connection**

Did I something wrong? 
Thanks for you answer.
Régis

**Comment by Eeems** [comment]
This duplicates #731

Please read the warnings on the toltec website carefully, as you are attempting to install toltec on an unsupported version.

For more information on why this matters: https://remarkable.guide/faqs.html#can-i-install-toltec-before-my-os-version-is-supported
