### ISSUE TITLE
Trouble installing toltec

### ISSUE THREAD

**Issue by eregen** [matteodelabre/toltec#845]
I have a remarkable 2 with software version 2.15.1.1189

I've ssh'ed into my device and pasted the command

sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)"

and got this:
wget: note: TLS certificate validation not implemented
writing to stdout

               100% |********************************************************************| 13501  0:00:00 ETA
written to stdout
Disk space seems to be enough.
rM2 Version 2.15.1.1189 - patch_39.2.01
Connecting to github.com (140.82.112.4:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer

I also tried the next alternative

sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" _ patch_xxx

but got the same error. Then I went to the Toltec webiste and followed their installation instructions. I pasted

wget http://toltec-dev.org/bootstrap
echo "37f6cc2a0c87dfe9b895c01a546315e9e43d87b9dc04e39b28e2c76ea87b1f7c bootstrap" | sha256sum -c && bash bootstrap

and then I got

Connecting to toltec-dev.org (5.161.99.157:80)
wget: can't open 'bootstrap': File exists
sha256sum: -: no checksum lines found

but when I tried any of the "opkg" commands I just get

-sh: opkg: command not found

Am I doing something wrong?

**Comment by Eeems** [comment]
> wget: can't open 'bootstrap': File exists

It looks like you already have a bootstrap file, but `sha256sum` is failing reading it. Try deleting the file and then downloading it again.

As for the ddvk-hacks installation error, it's unrelated to toltec. If you are installing toltec, you should be using the `ddvk-hacks` package to install ddvk-hacks instead of the automagic installer (https://remarkable.guide/faqs.html#can-i-install-toltec-at-the-same-time-as-ddvk-hacks).

**Comment by Eeems** [comment]
@eregen were you able to get further?

**Comment by Eeems** [comment]
@eregen poke? I will be closing this in a couple of weeks if there is no response, as I assume it's resolved.

**Comment by Eeems** [comment]
As there has been no update since this was opened in April, I'm closing this as stale. Feel free to open it again if you are still having issues.
