### ISSUE TITLE
toltecctl command not found

### ISSUE THREAD

**Issue by sanchitburkule** [matteodelabre/toltec#846]
**Describe the issue**
After installing the package using the wget command Im unable to do anything with it. I tried installing again, still the same problem

**To Reproduce**
Steps to reproduce the behaviour:
wget http://toltec-dev.org/bootstrap
echo "37f6cc2a0c87dfe9b895c01a546315e9e43d87b9dc04e39b28e2c76ea87b1f7c  bootstrap" | sha256sum -c && bash bootstrap

**Screenshots**
<img width="571" alt="Screenshot 2024-05-04 at 20 02 55" src="https://github.com/toltec-dev/toltec/assets/35194828/1e025e2f-27a7-4843-b638-054eeccf6821">

**Device information (please complete the following information):**
 - Device: RM2
 - OS version: 2.15

**Comment by Eeems** [comment]
`.entware` exists. Have you previously installed remarkable_entware? If so, you'll need to uninstall it before installing toltec.

**Comment by Eeems** [comment]
You said that this is the second time you've run the installation, but `toltecctl` isn't installed. What was the output the first time you ran it?

**Comment by sanchitburkule** [comment]
<img width="1440" alt="Screenshot 2024-05-05 at 10 05 12" src="https://github.com/toltec-dev/toltec/assets/35194828/1527bcc0-2856-4b9e-9ba8-905536c6a832">


I did a factory reset of the RM2 and now getting a different error for creating a directory.

**Comment by Eeems** [comment]
https://remarkable.guide/faqs.html#is-it-safe-to-factory-reset-my-device

Thank goodness you didn't soft-brick your device.

What does `systemctl status opt.mount` return?

**Comment by sanchitburkule** [comment]
<img width="607" alt="Screenshot 2024-05-05 at 14 15 38" src="https://github.com/toltec-dev/toltec/assets/35194828/3b2f008a-0725-4852-848b-aeb389b861b4">

**Comment by Eeems** [comment]
```
systemctl disable --now opt.mount
rm /lib/systemd/system/opt.mount
```

I think what happened is that you successfully installed toltec and then missed reading the output that instructs you to run a command to run to give your current shell access to toltec. The factory reset the  left some of the toltec install still in place in the OS partition, which needs to be cleaned up for bootstrap to work.

**Comment by sanchitburkule** [comment]
Got it, do i need to reinstall toltecctl after this?

**Comment by Eeems** [comment]
> Got it, do i need to reinstall toltecctl after this?

You will have to install toltec using bootstrap, as it's not installed. Make sure to read the installation output this time if you want to use the newly installed commands in the current shell session. Otherwise, just start a new SSH session.

**Comment by sanchitburkule** [comment]
Hey @Eeems thanks for all the help, it got sorted out.
