### ISSUE TITLE
kernelctl should no longer use `/etc/version`

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#885]
**Describe the issue**
Kernelctl uses `/etc/version` when creating a backup of the current kernel. As this stops being a unique value in newer OS builds, 

**To Reproduce**
Steps to reproduce the behaviour:
1. install kernelctl
2. run `kernelctl list` to see list of kernels

**Expected behaviour**
It should be using `RELEASE_VERSION` from `/usr/share/remarkable/update.conf` for the OS version number instead.

**Upstream issue**
N/A

**Screenshots**
![image](https://github.com/toltec-dev/toltec/assets/1176979/d26ba387-3391-4ae0-ac35-d38a60f69a72)

**System information:**
 - `toltecctl status` output: N/A
 - Package: kernelctl

**Additional context**
`toltecctl` has the following code available that kernelctl could call: https://github.com/toltec-dev/toltec/blob/eed41f1abede4150994186faa6a53612d90d88e0/package/toltec-bootstrap/toltecctl#L108-L110

**Comment by Eeems** [comment]
@Etn40ff would you be willing to make this change?

**Comment by Etn40ff** [comment]
> @Etn40ff would you be willing to make this change?

Sure

**Comment by Etn40ff** [comment]
It only took me a month https://github.com/toltec-dev/toltec/pull/905
