### ISSUE TITLE
bootstrap failed: missing dependencies for toltec-base: open-remarkable-shutdown

### ISSUE THREAD

**Issue by stefan-bergstein** [matteodelabre/toltec#907]
**Describe the issue**

`bash bootstrap` failed with

```
Downloading https://toltec-dev.org/stable/rm2os3/toltec-base_1.4-1_rm2os3.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for toltec-base:
 * 	open-remarkable-shutdown
 * opkg_install_cmd: Cannot install package toltec-base.
ERROR: Unexpected error on line bootstrap:260 in function main

```

**To Reproduce**
Steps to reproduce the behaviour:
1. Install OS version 3.3.2.1666
2. download bootstrap`wget http://toltec-dev.org/bootstrap`
3. Run bootstrap `echo "b87a085485404d2b000418b8ad44b52edd0293721f61427f2e427555ce9c6975  bootstrap" | sha256sum -c && bash bootstrap`

**Expected behaviour**
bootstrap run without error

**Screenshots**
n/a

**System information:**
```
Model: rm2 RM110
OS: 3.3.2.166
```

**Additional context**

**Comment by Eeems** [comment]
The package configuration does not include open-remarkable-shutdown:
https://github.com/toltec-dev/toltec/blob/dd081249f429a3c7653e5f3e153a687c879b025c/package/toltec-base/package#L14-L18

Yet for some reason the created package contains it:
```
Package: toltec-base
Description: Metapackage defining the base set of packages in a Toltec install
Homepage: https://toltec-dev.org/
Version: 1.4-1
Section: utils
Maintainer: Eeems <eeems@eeems.email>
License: MIT
Architecture: rm2os3
Depends: ca-certificates, entware-rc, launcherctl, open-remarkable-shutdown, rm2-suspend-fix, toltec-bootstrap, toltec-completion, toltec-deletions, wget-ssl
```
This likely is a bug with toltecmk.

**Comment by stefan-bergstein** [comment]
Workaround:
1.) Download open-remarkable-shutdown_1.0-3_rmallos2.ipk
2.) patch `bootstrap` at lin 260
```
    opkg install /home/root/open-remarkable-shutdown_1.0-3_rmallos2.ipk # <- add this line
    opkg install toltec-base
```
3.) run `bash bootstrap`

**Comment by Eeems** [comment]
I would not recommend most users do this, as open-remarkable-shutdown isn't working properly on 3.x for the rM2

**Comment by Havner** [comment]
Just stumbled upon this as well.

**Comment by Havner** [comment]
> The package configuration does not include open-remarkable-shutdown:
> 
> https://github.com/toltec-dev/toltec/blob/dd081249f429a3c7653e5f3e153a687c879b025c/package/toltec-base/package#L14-L18

Maybe I don't understand it, but it does include it:
`installdepends_rm1os3=(open-remarkable-shutdown)`

So it just looks like it should be removed from the package file.

**Comment by Eeems** [comment]
I've written a simple test in toltecmk to validate that installdepends is parsed properly. It has identified a bug with the recipe parser that is causing it to have invalid values. I'm now trying to grok the parser code to determine what is wrong and how to fix it.

**Comment by Eeems** [comment]
0.3.3 of toltecmk has been published to fix the issue, I'll have to integrate it and push through an emergency fix to stable tomorrow.

**Comment by Eeems** [comment]
This should now be resolved.
