### ISSUE TITLE
Define and automatically enforce a code style

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/toltec#95]
* [x] Define a common code style for the project (e.g. as a shfmt config).
* [x] Add a `make lint` target for checking code style issues and optionally automatically fixing them (e.g. using shfmt).
* [x] Add a step in the `pr` workflow for automatically checking code style.
* [x] Create a contributing guide in which this code style is mentioned.

**Comment by raisjn** [comment]
> Add a step in the pr workflow for automatically ~~checking~~ fixing code style.

**Comment by matteodelabre** [comment]
I’m not sure we want to automatically perform a potentially destructive operation on the code. But I agree that we at least need a target for automatically and locally fixing code style issues.

**Comment by raisjn** [comment]
if the linter can detect there is a style problem, why can't it fix it? what is a destructive behavior you are thinking of?

re: lint enforcement, it seems like work flow would be: make commit, submit pr, get style check enforcement, go back and run 'make lint' or similar. (am i understanding right? or does the style check also make suggestions in the pr?) 

this is requiring every contributor to install tools and adhere to this project guidelines, when it only needs to be done in one place, adding to everyone's overhead by a fixed amount

**Comment by matteodelabre** [comment]
> if the linter can detect there is a style problem, why can't it fix it? what is a destructive behavior you are thinking of?

You’re right that it should. It would only be potentially destructive if the workflow changed existing commits instead of pushing a new one which fixes the issues, which I doubt is sensible to do. [This action](https://github.com/wearerequired/lint-action) seems to have implemented this kind of behavior, but it doesn’t support `shfmt` currently (could be easily added though).

> re: lint enforcement, it seems like work flow would be: make commit, submit pr, get style check enforcement, go back and run 'make lint' or similar. (am i understanding right? or does the style check also make suggestions in the pr?)

As I’ve implemented it in #96, formatting/linting issues show up in the CI log, but are not presented nicely to users. This is also something that is implemented in [wearerequired/lint-action](https://github.com/wearerequired/lint-action).

> this is requiring every contributor to install tools and adhere to this project guidelines, when it only needs to be done in one place, adding to everyone's overhead by a fixed amount

I agree. But it’s a first step in the right direction, IMO. We can add automation later.
